const fs = require('fs');

// Load existing words
const existingWords = JSON.parse(fs.readFileSync('data/words.json', 'utf-8'));
let lastId = existingWords.length > 0 ? Math.max(...existingWords.map(w => w.id)) : 0;

// 200 Additional A1 Words
const a1_words = [
  ["almohada", "pillow", "noun", "soft white pillow bed"],
  ["sábana", "bed sheet", "noun", "clean white bed sheet"],
  ["manta", "blanket", "noun", "warm cozy blanket sofa"],
  ["toalla", "towel", "noun", "clean bath towel"],
  ["jabón", "soap", "noun", "bar of scented soap"],
  ["champú", "shampoo", "noun", "shampoo bottle bathroom"],
  ["cepillo", "brush", "noun", "hair brush vanity"],
  ["peine", "comb", "noun", "hair comb dresser"],
  ["espejo", "mirror", "noun", "bathroom wall mirror"],
  ["armario", "wardrobe / closet", "noun", "wooden clothes wardrobe"],
  ["cajón", "drawer", "noun", "open wooden drawer"],
  ["estante", "shelf", "noun", "wooden wall shelf books"],
  ["alfombra", "carpet / rug", "noun", "cozy living room rug"],
  ["cortina", "curtain", "noun", "window curtains elegant"],
  ["sofá", "sofa / couch", "noun", "comfortable living room sofa"],
  ["sillón", "armchair", "noun", "cozy reading armchair"],
  ["lámpara", "lamp", "noun", "table reading lamp glowing"],
  ["cuadro", "painting / picture", "noun", "framed art painting wall"],
  ["reloj", "clock / watch", "noun", "wall clock time"],
  ["jarrón", "vase", "noun", "flower vase table"],
  ["flor", "flower", "noun", "blooming colorful flower"],
  ["planta", "plant", "noun", "green potted indoor plant"],
  ["balcón", "balcony", "noun", "cozy apartment balcony view"],
  ["terraza", "terrace / patio", "noun", "sunny patio terrace chairs"],
  ["jardín", "garden", "noun", "green flowering garden path"],
  ["garaje", "garage", "noun", "home garage car parking"],
  ["sótano", "basement", "noun", "basement storage room"],
  ["techo", "ceiling / roof", "noun", "house roof tiles sky"],
  ["pared", "wall", "noun", "modern living room wall"],
  ["suelo", "floor", "noun", "wooden parquet floor"],
  ["pasillo", "hallway / corridor", "noun", "bright home hallway"],
  ["escalera", "stairs", "noun", "wooden home staircase"],
  ["ascensor", "elevator", "noun", "modern elevator doors"],
  ["entrada", "entrance", "noun", "house front door entrance"],
  ["salida", "exit", "noun", "exit sign door"],
  ["cocina", "kitchen", "noun", "modern clean kitchen"],
  ["comedor", "dining room", "noun", "dining table chairs set"],
  ["dormitorio", "bedroom", "noun", "cozy master bedroom"],
  ["baño", "bathroom", "noun", "clean modern bathroom"],
  ["oficina", "office", "noun", "desk laptop workspace office"],
  ["tienda", "shop / store", "noun", "boutique shop front"],
  ["mercado", "market", "noun", "fresh food market stall"],
  ["supermercado", "supermarket", "noun", "supermarket aisles cart"],
  ["panadería", "bakery", "noun", "fresh bakery bread pastries"],
  ["carnicería", "butcher shop", "noun", "fresh meat butcher shop"],
  ["pescadería", "fish market", "noun", "fresh seafood fish stall"],
  ["frutería", "fruit shop", "noun", "fruit stand apples oranges"],
  ["farmacia", "pharmacy", "noun", "pharmacy store green cross"],
  ["librería", "bookstore", "noun", "cozy bookstore shelves"],
  ["papelería", "stationery shop", "noun", "stationery store notebooks"],
  ["banco", "bank", "noun", "bank building front"],
  ["correos", "post office", "noun", "post office parcel delivery"],
  ["cine", "cinema / movie theater", "noun", "cinema auditorium seats"],
  ["teatro", "theater", "noun", "theater stage red curtains"],
  ["museo", "museum", "noun", "art museum gallery"],
  ["parque", "park", "noun", "green city park trees"],
  ["plaza", "square / plaza", "noun", "town square fountain"],
  ["calle", "street", "noun", "city street walking path"],
  ["avenida", "avenue", "noun", "broad city avenue trees"],
  ["puente", "bridge", "noun", "scenic river bridge"],
  ["estación", "station", "noun", "train station platform"],
  ["aeropuerto", "airport", "noun", "airport departure terminal"],
  ["parada", "bus stop", "noun", "city bus stop shelter"],
  ["puerto", "port / harbor", "noun", "marina harbor boats"],
  ["hotel", "hotel", "noun", "luxury hotel building"],
  ["restaurante", "restaurant", "noun", "restaurant dining table"],
  ["cafetería", "café / coffee shop", "noun", "cozy café table coffee"],
  ["bar", "bar / pub", "noun", "cozy tapas bar counter"],
  ["hospital", "hospital", "noun", "hospital entrance building"],
  ["clínica", "clinic", "noun", "medical clinic reception"],
  ["escuela", "school", "noun", "elementary school classroom"],
  ["colegio", "school / college", "noun", "school building playground"],
  ["universidad", "university", "noun", "university campus buildings"],
  ["biblioteca", "library", "noun", "quiet library books desk"],
  ["gimnasio", "gym", "noun", "fitness gym weights equipment"],
  ["piscina", "swimming pool", "noun", "outdoor resort swimming pool"],
  ["estadio", "stadium", "noun", "sports stadium field lights"],
  ["playa", "beach", "noun", "sunny ocean sand beach"],
  ["mar", "sea", "noun", "blue ocean sea waves"],
  ["río", "river", "noun", "flowing mountain river"],
  ["lago", "lake", "noun", "serene mountain blue lake"],
  ["montaña", "mountain", "noun", "snowy mountain peak sky"],
  ["bosque", "forest / woods", "noun", "lush green forest trees"],
  ["campo", "countryside / field", "noun", "green meadow field sky"],
  ["isla", "island", "noun", "tropical island palm ocean"],
  ["sol", "sun", "noun", "bright golden sun sky"],
  ["luna", "moon", "noun", "glowing full moon night"],
  ["estrella", "star", "noun", "starry night sky stars"],
  ["nube", "cloud", "noun", "white fluffy sky clouds"],
  ["lluvia", "rain", "noun", "rain drops window street"],
  ["nieve", "snow", "noun", "winter white falling snow"],
  ["viento", "wind", "noun", "blowing wind autumn leaves"],
  ["fuego", "fire", "noun", "cozy fireplace flame"],
  ["aire", "air", "noun", "fresh clear blue sky air"],
  ["tierra", "earth / land", "noun", "planet earth soil green"],
  ["agua", "water", "noun", "clear pouring water glass"],
  ["pan", "bread", "noun", "loaf of fresh baked bread"],
  ["leche", "milk", "noun", "glass of fresh white milk"],
  ["queso", "cheese", "noun", "yellow cheese wedge board"],
  ["mantequilla", "butter", "noun", "fresh butter dish block"],
  ["huevo", "egg", "noun", "fresh farm eggs bowl"],
  ["carne", "meat", "noun", "grilled beef steak plate"],
  ["pollo", "chicken", "noun", "roasted chicken dish"],
  ["pescado", "fish", "noun", "cooked fresh fish meal"],
  ["arroz", "rice", "noun", "steamed white rice bowl"],
  ["pasta", "pasta", "noun", "italian spaghetti pasta meal"],
  ["sopa", "soup", "noun", "steaming vegetable soup bowl"],
  ["ensalada", "salad", "noun", "fresh green salad bowl"],
  ["fruta", "fruit", "noun", "colorful fresh fruit basket"],
  ["manzana", "apple", "noun", "ripe red fresh apple"],
  ["plátano", "banana", "noun", "bunch of yellow bananas"],
  ["naranja", "orange", "noun", "juicy fresh orange fruit"],
  ["limón", "lemon", "noun", "yellow fresh lemon slices"],
  ["fresa", "strawberry", "noun", "sweet red strawberries"],
  ["uva", "grape", "noun", "purple juicy grapes vine"],
  ["tomate", "tomato", "noun", "ripe red fresh tomatoes"],
  ["patata", "potato", "noun", "fresh potatoes wooden table"],
  ["zanahoria", "carrot", "noun", "fresh orange carrots"],
  ["cebolla", "onion", "noun", "fresh white bulb onion"],
  ["ajo", "garlic", "noun", "garlic cloves bulb table"],
  ["sal", "salt", "noun", "white salt shaker spice"],
  ["pimienta", "pepper", "noun", "black pepper shaker spice"],
  ["aceite", "oil", "noun", "olive oil bottle pouring"],
  ["vinagre", "vinegar", "noun", "glass vinegar bottle salad"],
  ["azúcar", "sugar", "noun", "white sugar bowl spoon"],
  ["café", "coffee", "noun", "steaming coffee cup saucer"],
  ["té", "tea", "noun", "hot tea cup lemon slice"],
  ["zumo", "juice", "noun", "fresh orange juice glass"],
  ["vino", "wine", "noun", "red wine glass bottle"],
  ["cerveza", "beer", "noun", "cold draft beer mug foam"],
  ["camisa", "shirt", "noun", "collared dress shirt buttoned"],
  ["camiseta", "t-shirt", "noun", "casual cotton t-shirt"],
  ["pantalón", "pants / trousers", "noun", "denim jeans trousers"],
  ["falda", "skirt", "noun", "stylish summer skirt outfit"],
  ["vestido", "dress", "noun", "elegant summer dress fashion"],
  ["chaqueta", "jacket", "noun", "warm zip jacket coat"],
  ["abrigo", "coat", "noun", "heavy winter coat rack"],
  ["jersey", "sweater", "noun", "warm knit sweater folded"],
  ["zapato", "shoe", "noun", "pair of leather shoes"],
  ["bota", "boot", "noun", "pair of leather boots"],
  ["zapatilla", "sneaker / slipper", "noun", "sports sneakers shoes"],
  ["calcetín", "sock", "noun", "pair of warm wool socks"],
  ["sombrero", "hat", "noun", "stylish sun hat beach"],
  ["gorra", "cap", "noun", "baseball cap sports"],
  ["guante", "glove", "noun", "pair of winter gloves"],
  ["bufanda", "scarf", "noun", "cozy knit winter scarf"],
  ["cinturón", "belt", "noun", "leather waist belt buckle"],
  ["bolso", "handbag / purse", "noun", "stylish leather handbag"],
  ["mochila", "backpack", "noun", "travel hiking backpack"],
  ["maleta", "suitcase", "noun", "rolling travel suitcase"],
  ["gafas", "glasses", "noun", "modern eyeglasses frame desk"],
  ["reloj", "watch", "noun", "wrist watch time clock"],
  ["paraguas", "umbrella", "noun", "open umbrella rainy day"],
  ["llave", "key", "noun", "metal door key keychain"],
  ["moneda", "coin", "noun", "silver gold coins money"],
  ["billete", "banknote / ticket", "noun", "paper money cash bill"],
  ["cartera", "wallet", "noun", "leather pocket wallet cash"],
  ["tarjeta", "card", "noun", "credit card payment chip"],
  ["móvil", "mobile phone", "noun", "modern smartphone screen"],
  ["ordenador", "computer", "noun", "desktop computer screen desk"],
  ["portátil", "laptop", "noun", "open laptop computer desk"],
  ["pantalla", "screen / display", "noun", "computer monitor display screen"],
  ["teclado", "keyboard", "noun", "computer typing keyboard desk"],
  ["ratón", "mouse", "noun", "computer optical mouse pad"],
  ["camisa", "button shirt", "noun", "neatly ironed shirt rack"],
  ["bolígrafo", "pen", "noun", "blue ink ballpoint pen"],
  ["lápiz", "pencil", "noun", "wooden graphite pencil desk"],
  ["papel", "paper", "noun", "clean white paper sheet"],
  ["cuaderno", "notebook", "noun", "open spiral notebook desk"],
  ["libro", "book", "noun", "open reading book desk"],
  ["periódico", "newspaper", "noun", "morning newspaper reading coffee"],
  ["revista", "magazine", "noun", "glossy magazine pages table"],
  ["carta", "letter / menu", "noun", "paper letter envelope seal"],
  ["paquete", "parcel / package", "noun", "cardboard parcel box delivery"],
  ["regalo", "gift / present", "noun", "wrapped gift box ribbon"],
  ["fiesta", "party", "noun", "celebration party confetti balloons"],
  ["música", "music", "noun", "headphones music note glowing"],
  ["canción", "song", "noun", "singer microphone song stage"],
  ["película", "movie / film", "noun", "movie film reel cinema"],
  ["juego", "game", "noun", "board game pieces table"],
  ["deporte", "sport", "noun", "sports balls equipment set"],
  ["fútbol", "soccer", "noun", "soccer ball grass field"],
  ["baloncesto", "basketball", "noun", "basketball court hoop net"],
  ["tenis", "tennis", "noun", "tennis racket ball court"],
  ["natación", "swimming", "noun", "swimmer ocean pool water"],
  ["carrera", "race / run", "noun", "runners race track finish line"],
  ["viaje", "trip / journey", "noun", "airplane travel map passport"],
  ["vacaciones", "vacation / holiday", "noun", "resort tropical beach lounge"],
  ["trabajo", "job / work", "noun", "office business workspace desk"],
  ["clase", "class / lesson", "noun", "classroom teacher blackboard"],
  ["examen", "exam / test", "noun", "student writing exam paper"],
  ["tarea", "homework / task", "noun", "studying desk homework books"],
  ["pregunta", "question", "noun", "question mark symbol sign"],
  ["respuesta", "answer", "noun", "checkmark green answer correct"],
  ["problema", "problem", "noun", "puzzle missing piece problem"],
  ["solución", "solution", "noun", "glowing lightbulb idea solution"],
  ["ejemplo", "example", "noun", "handwriting whiteboard example"],
  ["número", "number", "noun", "colorful numbers block set"],
  ["nombre", "name", "noun", "hello my name is badge tag"],
  ["apellido", "surname / last name", "noun", "passport document identity form"],
  ["edad", "age", "noun", "birthday cake candles age"],
  ["fecha", "date", "noun", "calendar page date circle"],
  ["día", "day", "noun", "sunny daytime sky landscape"],
  ["noche", "night", "noun", "starry moonlit night house"],
  ["semana", "week", "noun", "weekly calendar planner desk"],
  ["mes", "month", "noun", "monthly calendar page year"],
  ["año", "year", "noun", "new year celebration fireworks"],
  ["hora", "hour / time", "noun", "clock hands hour mark"],
  ["minuto", "minute", "noun", "stopwatch timer minute mark"],
  ["segundo", "second", "noun", "digital stopwatch race timer"]
];

// 200 Additional A2 Words
const a2_words = [
  ["alojamiento", "accommodation / lodging", "noun", "hotel resort room accommodation"],
  ["reserva", "reservation / booking", "noun", "hotel reservation tablet confirm"],
  ["recepción", "reception / front desk", "noun", "hotel front desk reception key"],
  ["pasaje", "boarding pass / ticket", "noun", "airplane boarding pass passport"],
  ["embarque", "boarding gate", "noun", "airport departure gate plane"],
  ["aduana", "customs", "noun", "airport customs border check"],
  ["equipaje", "luggage / baggage", "noun", "travel suitcases baggage cart"],
  ["facturación", "check-in", "noun", "airport check-in counter desk"],
  ["pasajero", "passenger", "noun", "train passenger window view"],
  ["conductor", "driver", "noun", "car driver steering wheel road"],
  ["camarero", "waiter", "noun", "restaurant waiter bringing dish"],
  ["cocinero", "chef / cook", "noun", "professional chef cooking kitchen"],
  ["médico", "doctor", "noun", "doctor stethoscope coat hospital"],
  ["enfermero", "nurse", "noun", "nurse assisting patient clinic"],
  ["dentista", "dentist", "noun", "dentist exam chair smile"],
  ["veterinario", "veterinarian", "noun", "veterinarian inspecting dog puppy"],
  ["policía", "police officer", "noun", "police officer patrol uniform"],
  ["bombero", "firefighter", "noun", "firefighter helmet truck equipment"],
  ["profesor", "teacher / professor", "noun", "teacher explaining classroom board"],
  ["estudiante", "student", "noun", "college student book campus"],
  ["abogado", "lawyer", "noun", "lawyer briefcase courtroom office"],
  ["ingeniaro", "engineer", "noun", "engineer blueprint helmet site"],
  ["arquitecto", "architect", "noun", "architect model drafting desk"],
  ["mecanico", "mechanic", "noun", "car mechanic repair garage"],
  ["peluquero", "hairdresser", "noun", "hairdresser cutting hair salon"],
  ["cartero", "mail carrier", "noun", "mailman postal delivery bag"],
  ["vendedor", "salesperson", "noun", "store shop assistant helping customer"],
  ["cliente", "customer / client", "noun", "customer paying counter smile"],
  ["jefe", "boss / manager", "noun", "business manager leading meeting"],
  ["empleado", "employee", "noun", "office worker typing laptop"],
  ["compañero", "colleague / classmate", "noun", "two coworkers collaborating desk"],
  ["vecino", "neighbor", "noun", "friendly neighbor waving garden"],
  ["amigo", "friend", "noun", "two best friends smiling cafe"],
  ["pareja", "couple / partner", "noun", "happy couple walking park"],
  ["marido", "husband", "noun", "husband smiling home living room"],
  ["mujer", "wife / woman", "noun", "happy wife smiling home"],
  ["hijo", "son", "noun", "father and young son playing"],
  ["hija", "daughter", "noun", "mother and young daughter hugging"],
  ["padre", "father", "noun", "loving father smiling family"],
  ["madre", "mother", "noun", "caring mother smiling kitchen"],
  ["hermano", "brother", "noun", "two brothers smiling outdoors"],
  ["hermana", "sister", "noun", "two sisters laughing together"],
  ["abuelo", "grandfather", "noun", "kind grandfather smiling garden"],
  ["abuela", "grandmother", "noun", "kind grandmother baking kitchen"],
  ["tio", "uncle", "noun", "friendly uncle playing kids"],
  ["tia", "aunt", "noun", "friendly aunt reading child"],
  ["primo", "cousin", "noun", "cousins playing garden summer"],
  ["sobrino", "nephew", "noun", "young nephew playing park"],
  ["sobrina", "niece", "noun", "young niece playing playground"],
  ["familia", "family", "noun", "happy family embracing sunset"],
  ["cuerpo", "body", "noun", "human body health fitness"],
  ["cabeza", "head", "noun", "person head face smile"],
  ["pelo", "hair", "noun", "long healthy hair woman"],
  ["cara", "face", "noun", "cheerful woman smiling face"],
  ["ojo", "eye", "noun", "macro close up eye iris"],
  ["nariz", "nose", "noun", "close up person nose smile"],
  ["boca", "mouth", "noun", "smiling mouth teeth white"],
  ["diente", "tooth", "noun", "clean white healthy teeth"],
  ["oreja", "ear", "noun", "person ear listening music"],
  ["cuello", "neck", "noun", "woman neck shoulders portrait"],
  ["hombro", "shoulder", "noun", "athlete shoulder muscles fitness"],
  ["brazo", "arm", "noun", "strong muscular arm fitness"],
  ["codo", "elbow", "noun", "arm joint elbow fitness"],
  ["mano", "hand", "noun", "open human hand fingers"],
  ["dedo", "finger", "noun", "pointing finger hand gesture"],
  ["pecho", "chest", "noun", "chest posture fitness health"],
  ["espalda", "back", "noun", "spine back posture physical"],
  ["estómago", "stomach / belly", "noun", "healthy belly stomach digestion"],
  ["pierna", "leg", "noun", "runner legs track sport"],
  ["rodilla", "knee", "noun", "knee joint leg exercise"],
  ["pie", "foot", "noun", "bare feet sandy beach"],
  ["piel", "skin", "noun", "smooth healthy skin care"],
  ["sangre", "blood", "noun", "heart blood drop health"],
  ["corazón", "heart", "noun", "red glowing heart symbol"],
  ["salud", "health", "noun", "healthy lifestyle fresh food sport"],
  ["enfermedad", "disease / illness", "noun", "medical care medicine illness"],
  ["dolor", "pain / ache", "noun", "person holding head headache pain"],
  ["fiebre", "fever", "noun", "thermometer fever checking patient"],
  ["gripe", "flu / cold", "noun", "sick person tissue tea blanket"],
  ["tos", "cough", "noun", "person coughing hand mouth"],
  ["herida", "wound / injury", "noun", "bandage wound knee care"],
  ["medicina", "medicine / drug", "noun", "pills medicine bottle pharmacy"],
  ["pastilla", "pill / tablet", "noun", "medical pills blister pack"],
  ["jarabe", "syrup / medicine", "noun", "cough syrup bottle spoon"],
  ["venda", "bandage / dressing", "noun", "medical cotton bandage roll"],
  ["receta", "prescription / recipe", "noun", "doctor prescription note paper"],
  ["cita", "appointment / date", "noun", "calendar appointment reminder pen"],
  ["clima", "climate / weather", "noun", "sunny weather clouds blue sky"],
  ["temperatura", "temperature", "noun", "thermometer weather degree warm"],
  ["grado", "degree", "noun", "temperature degrees indicator celsius"],
  ["estación", "season", "noun", "four seasons trees autumn winter spring"],
  ["primavera", "spring", "noun", "spring blooming colorful flowers"],
  ["verano", "summer", "noun", "sunny summer beach palm tree"],
  ["otoño", "autumn / fall", "noun", "autumn golden leaves park path"],
  ["invierno", "winter", "noun", "snowy wintry landscape trees"],
  ["paisaje", "landscape / scenery", "noun", "scenic mountain valley landscape"],
  ["naturaleza", "nature", "noun", "lush green forest nature river"],
  ["medioambiente", "environment", "noun", "green earth planet care sprout"],
  ["reciclaje", "recycling", "noun", "green recycling sign bins"],
  ["basura", "trash / garbage", "noun", "sorted trash bin recycling"],
  ["contaminación", "pollution", "noun", "smokestack factory smoke sky"],
  ["tráfico", "traffic", "noun", "city traffic cars highway street"],
  ["vehículo", "vehicle", "noun", "modern electric car road"],
  ["coche", "car", "noun", "blue sedan car driving road"],
  ["autobús", "bus", "noun", "city transit bus stop"],
  ["tren", "train", "noun", "high speed train tracks station"],
  ["metro", "subway / metro", "noun", "underground subway metro train"],
  ["tranvía", "tram", "noun", "city street tram tracks"],
  ["avión", "airplane", "noun", "commercial airplane flying sky"],
  ["barco", "boat / ship", "noun", "sailing boat ocean sea"],
  ["bicicleta", "bicycle / bike", "noun", "classic city bicycle basket"],
  ["moto", "motorcycle", "noun", "modern motorcycle highway road"],
  ["camión", "truck", "noun", "cargo delivery truck highway"],
  ["taxista", "taxi driver", "noun", "yellow taxi cab city street"],
  ["billete", "ticket", "noun", "transit passenger ticket hand"],
  ["horario", "schedule / timetable", "noun", "train departure timetable screen"],
  ["retraso", "delay", "noun", "flight delay board clock"],
  ["llegada", "arrival", "noun", "airport arrivals terminal sign"],
  ["salida", "departure", "noun", "airport departures terminal sign"],
  ["vuelo", "flight", "noun", "airplane wing view clouds sky"],
  ["asiento", "seat", "noun", "airplane window seat comfortable"],
  ["pasillo", "aisle / corridor", "noun", "airplane interior aisle seats"],
  ["ventana", "window", "noun", "open sunny room window view"],
  ["equipaje", "hand luggage", "noun", "carry on suitcase airport"],
  ["maletero", "trunk / boot", "noun", "car open trunk suitcase"],
  ["gasolinera", "gas station", "noun", "fueling car gas station pump"],
  ["taller", "repair shop / workshop", "noun", "mechanic auto repair workshop"],
  ["aparcamiento", "parking lot", "noun", "city parking garage cars"],
  ["multa", "fine / ticket", "noun", "traffic ticket windshield car"],
  ["semáforo", "traffic light", "noun", "city red green traffic light"],
  ["cruce", "intersection / crossing", "noun", "pedestrian crosswalk city street"],
  ["acera", "sidewalk / pavement", "noun", "city street sidewalk walking"],
  ["peptón", "pedestrian", "noun", "pedestrians walking city crosswalk"],
  ["carretera", "highway / road", "noun", "scenic open highway road"],
  ["autopista", "freeway / motorway", "noun", "multi lane highway cars"],
  ["velocidad", "speed", "noun", "car speedometer speed dial"],
  ["límite", "limit", "noun", "speed limit road sign"],
  ["peligro", "danger / hazard", "noun", "warning danger sign triangle"],
  ["seguridad", "safety / security", "noun", "seatbelt fastened safety car"],
  ["accidente", "accident", "noun", "car breakdown tow truck safety"],
  ["seguro", "insurance", "noun", "car insurance policy document key"],
  ["contrato", "contract", "noun", "signing legal contract pen"],
  ["empresa", "company / business", "noun", "modern skyscraper office building"],
  ["negocio", "business", "noun", "business handshake meeting room"],
  ["reunión", "meeting", "noun", "corporate business team meeting table"],
  ["proyecto", "project", "noun", "blueprint project desk planning"],
  ["informe", "report", "noun", "financial data report chart desk"],
  ["presupuesto", "budget", "noun", "calculator coins budget planner"],
  ["cuenta", "account / bill", "noun", "bank account statement card"],
  ["impuesto", "tax", "noun", "tax calculation form coins"],
  ["factura", "invoice / bill", "noun", "paper store invoice receipt"],
  ["precio", "price", "noun", "price tag discount store"],
  ["descuento", "discount", "noun", "sale percentage discount tag"],
  ["oferta", "offer / deal", "noun", "special offer sale sign"],
  ["compra", "purchase / shopping", "noun", "shopping bags customer store"],
  ["venta", "sale", "noun", "for sale real estate sign"],
  ["ganancia", "profit / gain", "noun", "sprouting coin plant profit"],
  ["pérdida", "loss", "noun", "falling stock chart loss red"],
  ["inversión", "investment", "noun", "growing money investment plant"],
  ["ahorro", "savings", "noun", "piggy bank coins savings"],
  ["tarjeta", "credit card", "noun", "paying credit card terminal"],
  ["efectivo", "cash", "noun", "hand holding cash paper bills"],
  ["moneda", "currency / coin", "noun", "foreign exchange currency coins"],
  ["cambio", "exchange / change", "noun", "money currency exchange sign"],
  ["cajero", "ATM / cashier", "noun", "using ATM cash machine"],
  ["recibo", "receipt", "noun", "store purchase receipt hand"],
  ["garantía", "guarantee / warranty", "noun", "golden warranty seal stamp"],
  ["calidad", "quality", "noun", "five star quality rating gold"],
  ["marca", "brand", "noun", "luxury brand logo tag"],
  ["producto", "product", "noun", "packaged retail product box"],
  ["servicio", "service", "noun", "customer support service headset"],
  ["cliente", "client", "noun", "happy business client handshake"],
  ["opinión", "opinion / review", "noun", "star rating review customer"],
  ["consejo", "advice / tip", "noun", "wise mentor advising young person"],
  ["ayuda", "help / assistance", "noun", "helping hand support unity"],
  ["experiencia", "experience", "noun", "mountaineer summit experience view"],
  ["conocimiento", "knowledge", "noun", "glowing lightbulb brain book"],
  ["habilidad", "skill / ability", "noun", "skilful hands wood carving art"],
  ["éxito", "success", "noun", "champion trophy celebration win"],
  ["fracaso", "failure", "noun", "person learning from mistake thoughts"],
  ["meta", "goal / target", "noun", "archery bullseye target arrow"],
  ["sueño", "dream / sleep", "noun", "dreamer starry sky glowing light"],
  ["deseo", "wish / desire", "noun", "blowing dandelion seeds wish"],
  ["esperanza", "hope", "noun", "sunrise shining over horizon hope"],
  ["alegría", "joy / happiness", "noun", "happy person jumping joy beach"],
  ["tristeza", "sadness", "noun", "sad person window rain drop"],
  ["miedo", "fear", "noun", "brave climber overcoming fear summit"],
  ["sorpresa", "surprise", "noun", "surprised woman unboxing gift"],
  ["vergüenza", "shame / embarrassment", "noun", "blushing shy person face"],
  ["orgullo", "pride", "noun", "graduate proud holding diploma"],
  ["amor", "love", "noun", "holding heart symbol hands"],
  ["odio", "hatred", "noun", "dramatic storm cloud lighting sky"],
  ["paz", "peace", "noun", "white dove flying blue sky peace"],
  ["guerra", "war / conflict", "noun", "peaceful olive branch over helmet"],
  ["libertad", "freedom", "noun", "soaring bird sky freedom"],
  ["justicia", "justice", "noun", "scales of justice gold balance"],
  ["ley", "law", "noun", "gavel legal book courtroom"],
  ["derecho", "right / law", "noun", "human rights voting ballot box"],
  ["deber", "duty / obligation", "noun", "checklist completed checkmark desk"]
];

// 200 Additional B1 Words
const b1_words = [
  ["investigación", "research / investigation", "noun", "laboratory scientist research microscope"],
  ["desarrollo", "development / growth", "noun", "sprout growing into tree progress"],
  ["tecnología", "technology", "noun", "glowing digital technology circuit"],
  ["ciencia", "science", "noun", "scientific flasks chemistry lab"],
  ["sociedad", "society", "noun", "diverse group of people community"],
  ["gobierno", "government", "noun", "parliament building capital city"],
  ["política", "politics / policy", "noun", "podium microphone debate politics"],
  ["economía", "economy", "noun", "growing economic chart graph"],
  ["industria", "industry", "noun", "modern factory manufacturing plant"],
  ["comercio", "commerce / trade", "noun", "cargo container ship harbor trade"],
  ["mercancía", "merchandise / goods", "noun", "warehouse inventory boxes goods"],
  ["transporte", "transportation", "noun", "city logistics transport trucks train"],
  ["comunicación", "communication", "noun", "global network communication icons"],
  ["educación", "education", "noun", "university graduation students cap"],
  ["cultura", "culture", "noun", "traditional folk festival art dance"],
  ["arte", "art", "noun", "oil painting canvas studio artist"],
  ["literatura", "literature", "noun", "classic antique books library shelf"],
  ["poesía", "poetry", "noun", "fountain pen vintage manuscript poem"],
  ["teatro", "theater", "noun", "dramatic stage red curtains lights"],
  ["arquitectura", "architecture", "noun", "modern skyscraper architectural design"],
  ["historia", "history", "noun", "ancient Roman ruins history colosseum"],
  ["geografía", "geography", "noun", "globe map compass world atlas"],
  ["medio ambiente", "environment", "noun", "green sprout hands nature earth"],
  ["sostenibilidad", "sustainability", "noun", "wind turbines solar panels green"],
  ["biodiversidad", "biodiversity", "noun", "coral reef ocean wildlife green"],
  ["fauna", "fauna / wildlife", "noun", "wild lion jungle forest nature"],
  ["flora", "flora / vegetation", "noun", "lush green rainforest plants flora"],
  ["recurso", "resource", "noun", "pure water waterfall mountain resource"],
  ["energía", "energy", "noun", "solar panel array glowing sun"],
  ["petróleo", "oil / petroleum", "noun", "offshore oil rig sea platform"],
  ["gas", "gas / natural gas", "noun", "natural gas flame stove blue"],
  ["electricidad", "electricity", "noun", "glowing lightbulb power transmission"],
  ["infraestructura", "infrastructure", "noun", "suspension bridge highway modern"],
  ["urbanismo", "urban planning", "noun", "city aerial architectural model green"],
  ["vivienda", "housing", "noun", "modern apartment complex residential"],
  ["alquiler", "rent / lease", "noun", "apartment key hand lease contract"],
  ["hipoteca", "mortgage", "noun", "house model mini key document"],
  ["patrimonio", "heritage / assets", "noun", "historic castle heritage monument"],
  ["turismo", "tourism", "noun", "tourists sightseeing historic monument"],
  ["gastronomía", "gastronomy / cuisine", "noun", "gourmet chef dish restaurant plate"],
  ["nutrición", "nutrition", "noun", "fresh organic salad healthy food"],
  ["dieta", "diet", "noun", "balanced healthy food plate fitness"],
  ["caloría", "calorie", "noun", "healthy food counting fitness scale"],
  ["ejercicio", "exercise / workout", "noun", "fitness workout dumbbells gym"],
  ["gimnasia", "gymnastics / fitness", "noun", "gymnast balancing beam arena"],
  ["deportista", "athlete", "noun", "track athlete runner sprinting finish"],
  ["campeonato", "championship", "noun", "golden championship trophy winner"],
  ["entrenamiento", "training / practice", "noun", "athlete training track field coach"],
  ["competencia", "competition / contest", "noun", "swimming competition pool race"],
  ["rival", "rival / opponent", "noun", "chess game players facing board"],
  ["victoria", "victory / win", "noun", "athlete raising arms victory finish"],
  ["derrota", "defeat / loss", "noun", "defeated athlete sitting track effort"],
  ["premio", "award / prize", "noun", "shiny gold medal award ribbon"],
  ["trofeo", "trophy", "noun", "golden victory trophy podium"],
  ["espectáculo", "show / spectacle", "noun", "stage concert lights audience cheering"],
  ["concierto", "concert", "noun", "live music concert crowd stage"],
  ["festival", "festival", "noun", "outdoor music festival confetti crowd"],
  ["cineasta", "filmmaker / director", "noun", "film director camera set stage"],
  ["actor", "actor", "noun", "actor performing theater stage spotlight"],
  ["actriz", "actress", "noun", "actress red carpet movie premiere"],
  ["director", "director / manager", "noun", "movie director clapperboard camera"],
  ["productor", "producer", "noun", "music producer studio mixing desk"],
  ["guion", "script / screenplay", "noun", "film script typewriter pages desk"],
  ["escena", "scene", "noun", "movie film clapboard scene studio"],
  ["personaje", "character", "noun", "costumed actor theatrical character stage"],
  ["novela", "novel", "noun", "open hardcover fiction novel reading"],
  ["cuento", "short story / tale", "noun", "storybook fairy tale magic illustration"],
  ["poeta", "poet", "noun", "poet writing with feather pen paper"],
  ["ensayo", "essay / rehearsal", "noun", "writing academic essay notebook desk"],
  ["artículo", "article", "noun", "newspaper article magazine page headline"],
  ["noticia", "news item", "noun", "breaking news television broadcast screen"],
  ["periodista", "journalist / reporter", "noun", "journalist microphone press conference"],
  ["entrevista", "interview", "noun", "news interview microphone camera studio"],
  ["anuncio", "advertisement / announcement", "noun", "billboard street advertisement city"],
  ["publicidad", "advertising / publicity", "noun", "digital marketing advertising display"],
  ["marca", "brand / trademark", "noun", "designer brand logo tag luxury"],
  ["estrategia", "strategy", "noun", "chess board strategy pieces planning"],
  ["planificación", "planning", "noun", "wall calendar project planning notes"],
  ["gestión", "management / administration", "noun", "business manager reviewing charts desk"],
  ["organización", "organization / entity", "noun", "team working together meeting room"],
  ["administración", "administration", "noun", "corporate office administration desk"],
  ["liderazgo", "leadership", "noun", "business leader guiding team presentation"],
  ["colaboración", "collaboration", "noun", "hands together teamwork unity circle"],
  ["cooperación", "cooperation", "noun", "two partners shaking hands deal"],
  ["asociación", "association / partnership", "noun", "shaking hands corporate partnership"],
  ["fundación", "foundation / charity", "noun", "charity foundation building helping hands"],
  ["sindicato", "labor union", "noun", "workers union protest rally banners"],
  ["huelga", "strike", "noun", "peaceful workers strike sign rally"],
  ["manifestación", "demonstration / rally", "noun", "peaceful crowd rally march street"],
  ["protesta", "protest", "noun", "peaceful protest holding banners street"],
  ["reforma", "reform / renovation", "noun", "renovating house blueprint architecture"],
  ["cambio", "change / shift", "noun", "road sign direction change arrow"],
  ["proceso", "process", "noun", "gear mechanism working process engine"],
  ["etapa", "stage / phase", "noun", "staircase steps progression climbing"],
  ["fase", "phase", "noun", "moon phases astronomy sequence"],
  ["resultado", "result / outcome", "noun", "chart graph showing positive results"],
  ["efecto", "effect / impact", "noun", "water droplet ripple effect pond"],
  ["causa", "cause / reason", "noun", "domino falling chain reaction cause"],
  ["origen", "origin / source", "noun", "fresh water mountain spring source"],
  ["consecuencia", "consequence", "noun", "falling dominoes chain reaction consequence"],
  ["solución", "solution", "noun", "fitting puzzle piece key lock"],
  ["alternativa", "alternative / option", "noun", "road fork two paths choice sign"],
  ["opción", "option / choice", "noun", "multiple choice checkboxes form pen"],
  ["elección", "election / choice", "noun", "voting ballot box election citizen"],
  ["voto", "vote", "noun", "voter inserting paper ballot box"],
  ["candidato", "candidate", "noun", "political candidate podium speech flag"],
  ["campaña", "campaign", "noun", "campaign rally crowd signs stage"],
  ["discurso", "speech / address", "noun", "speaker addressing crowd microphone stage"],
  ["debates", "debates", "noun", "podium debate candidates speaking audience"],
  ["acuerdo", "agreement / deal", "noun", "signing official agreement document pen"],
  ["trata", "dealings / trade", "noun", "international trade container ship sea"],
  ["pacto", "pact / treaty", "noun", "diplomats shaking hands treaty document"],
  ["conflicto", "conflict / dispute", "noun", "chess pieces standoff board conflict"],
  ["discusión", "argument / debate", "noun", "two people debating room discussion"],
  ["negociación", "negotiation", "noun", "business negotiation table handshake"],
  ["compromiso", "commitment / compromise", "noun", "wedding rings engagement hands"],
  ["respeto", "respect", "noun", "respectful handshake bow greeting"],
  ["confianza", "trust / confidence", "noun", "climbing team rope trust summit"],
  ["sinceridad", "sincerity / honesty", "noun", "person speaking hand over heart"],
  ["lealtad", "loyalty", "noun", "loyal shepherd dog beside owner"],
  ["empatía", "empathy", "noun", "helping hand comforting friend support"],
  ["solidaridad", "solidarity", "noun", "volunteers packing food aid boxes"],
  ["igualdad", "equality", "noun", "balanced scales of justice equality"],
  ["diversidad", "diversity", "noun", "multicultural group of people smiling"],
  ["inclusión", "inclusion", "noun", "diverse team unity circle hands"],
  ["derechos", "rights", "noun", "human rights emblem voting ballot"],
  ["libertad", "freedom", "noun", "soaring eagle blue sky freedom"],
  ["seguridad", "security / safety", "noun", "cyber security shield digital lock"],
  ["riesgo", "risk", "noun", "tightrope walker balancing sky risk"],
  ["amenaza", "threat / hazard", "noun", "storm cloud approaching coastline threat"],
  ["protección", "protection / shield", "noun", "shield emblem protecting green sprout"],
  ["prevención", "prevention", "noun", "medical health checkup stethoscope prevention"],
  ["tratamiento", "treatment", "noun", "doctor patient consultation medical therapy"],
  ["curación", "healing / cure", "noun", "healing hands light green sprout"],
  ["vacuna", "vaccine", "noun", "medical vaccine vial syringe science"],
  ["síntoma", "symptom", "noun", "patient checking thermometer fever"],
  ["diagnóstico", "diagnosis", "noun", "doctor reviewing x-ray scan diagnosis"],
  ["análisis", "analysis / test", "noun", "laboratory blood sample test tube"],
  ["experimento", "experiment", "noun", "chemistry flask glowing reaction lab"],
  ["descubrimiento", "discovery", "noun", "astronomer observing telescope galaxy"],
  ["invento", "invention", "noun", "glowing Edison lightbulb vintage idea"],
  ["patente", "patent", "noun", "blueprint patent document stamp seal"],
  ["marca", "trademark", "noun", "registered trademark symbol document"],
  ["contrato", "lease / agreement", "noun", "signed lease document keys table"],
  ["cláusula", "clause", "noun", "reading contract legal clause pen"],
  ["condición", "condition / term", "noun", "document checkmark terms conditions"],
  ["requisito", "requirement / prerequisite", "noun", "checklist application requirement form"],
  ["solicitud", "application / request", "noun", "filling out paper application form"],
  ["permiso", "permit / permission", "noun", "approved official permit stamp document"],
  ["licencia", "license", "noun", "driver license card document desk"],
  ["pasaporte", "passport", "noun", "passport book stamps airport"],
  ["visado", "visa", "noun", "passport page visa entry stamp"],
  ["nacionalidad", "nationality", "noun", "passports world map nationality flags"],
  ["ciudadanía", "citizenship", "noun", "citizenship oath ceremony flag"],
  ["frontera", "border / frontier", "noun", "country border checkpoint river bridge"],
  ["aduana", "customs clearance", "noun", "airport customs border inspection"],
  ["extranjero", "foreigner / stranger", "noun", "traveler looking world map city"],
  ["idioma", "language", "noun", "speech bubbles world languages learning"],
  ["lengua", "tongue / language", "noun", "open dictionary words pages study"],
  ["traducción", "translation", "noun", "bilingual dictionary translator writing"],
  ["vocablo", "vocabulary word", "noun", "flashcard vocabulary learning book"],
  ["frase", "phrase / sentence", "noun", "typewriter printing phrase paper page"],
  ["oración", "sentence / prayer", "noun", "reading notebook written sentence pen"],
  ["palabra", "word", "noun", "wooden letter blocks spelling word"],
  ["letra", "letter / lyrics", "noun", "alphabet metal typeset letters ink"],
  ["sonido", "sound", "noun", "sound wave audio frequency equalizer"],
  ["voz", "voice", "noun", "microphone glowing sound wave voice"],
  ["acento", "accent / stress", "noun", "accent mark typed Spanish word"],
  ["pronunciación", "pronunciation", "noun", "person speaking practicing pronunciation mic"],
  ["gramática", "grammar", "noun", "grammar textbook open study desk"],
  ["ortografía", "spelling / orthography", "noun", "dictionary checking correct spelling pencil"],
  ["significado", "meaning / sense", "noun", "open dictionary pointing word definition"],
  ["definición", "definition", "noun", "dictionary page entry definition word"],
  ["sinónimo", "synonym", "noun", "connected word bubbles thesaurus study"],
  ["antónimo", "antonym", "noun", "opposite arrows word concept black white"],
  ["contexto", "context", "noun", "reading paragraph highlighted word context"],
  ["diálogo", "dialogue / conversation", "noun", "two people speaking speech bubbles cafe"],
  ["conversación", "conversation", "noun", "friends talking laughing coffee table"],
  ["comunicado", "press release / statement", "noun", "official document press statement seal"]
];

// 200 Additional B2 Words
const b2_words = [
  ["filosofía", "philosophy", "noun", "thinker statue philosophy reflection"],
  ["psicología", "psychology", "noun", "brain puzzle psychology concept"],
  ["sociología", "sociology", "noun", "connected people social network"],
  ["antropología", "anthropology", "noun", "ancient human skull museum excavation"],
  ["arqueología", "archaeology", "noun", "archaeologist digging ancient ruins brush"],
  ["astronomía", "astronomy", "noun", "stargazing observatory telescope galaxy"],
  ["astrofísica", "astrophysics", "noun", "deep space galaxy black hole nebula"],
  ["biología", "biology", "noun", "dna helix molecular biology lab"],
  ["química", "chemistry", "noun", "chemistry lab flasks colorful liquids"],
  ["física", "physics", "noun", "atom orbit quantum physics glowing"],
  ["matemáticas", "mathematics", "noun", "advanced math formulas blackboard"],
  ["geometría", "geometry", "noun", "compass architectural geometry drawings"],
  ["estadística", "statistics", "noun", "statistical data chart graphs analytics"],
  ["algoritmo", "algorithm", "noun", "computer code algorithm server screen"],
  ["inteligencia artificial", "artificial intelligence", "noun", "ai robot brain glowing tech"],
  ["robótica", "robotics", "noun", "robotic arm assembly factory line"],
  ["ciberseguridad", "cybersecurity", "noun", "digital lock cyber security shield"],
  ["biotecnología", "biotechnology", "noun", "biotech plant gene laboratory research"],
  ["genética", "genetics", "noun", "dna sequence genetic code strand"],
  ["nanotecnología", "nanotechnology", "noun", "microscopic nanotech molecular structure"],
  ["telecomunicación", "telecommunication", "noun", "satellite dish antenna communication space"],
  ["redes", "networks", "noun", "global digital network connections node"],
  ["servidor", "server / host", "noun", "datacenter server racks glowing lights"],
  ["plataforma", "platform", "noun", "digital cloud software platform dashboard"],
  ["software", "software", "noun", "software development code editor screen"],
  ["hardware", "hardware", "noun", "computer motherboard processor chip"],
  ["dispositivo", "device", "noun", "modern smart digital devices desk"],
  ["interfaz", "interface / UI", "noun", "user interface mobile design screen"],
  ["aplicación", "application / app", "noun", "smartphone screen displaying apps"],
  ["base de datos", "database", "noun", "database server storage cylinder data"],
  ["nube", "cloud storage", "noun", "cloud computing data sync icon"],
  ["almacenamiento", "storage", "noun", "high capacity ssd memory drive desk"],
  ["rendimiento", "performance / yield", "noun", "speedometer performance gauge racing"],
  ["eficiencia", "efficiency", "noun", "green energy efficiency scale chart"],
  ["optimización", "optimization", "noun", "gear tuning process optimization"],
  ["innovación", "innovation", "noun", "glowing lightbulb creative innovation idea"],
  ["vanguardia", "vanguard / forefront", "noun", "futuristic architectural building glass"],
  ["tendencia", "trend", "noun", "upward market trend graph arrow"],
  ["mercado", "market / marketplace", "noun", "stock exchange trading floor screens"],
  ["capitalismo", "capitalism", "noun", "stock market wall street building"],
  ["globalización", "globalization", "noun", "digital network connected globe earth"],
  ["democracia", "democracy", "noun", "voting ballot box democracy freedom"],
  ["soberanía", "sovereignty", "noun", "national emblem crown constitution seal"],
  ["constitución", "constitution", "noun", "historic constitution law book gavel"],
  ["parlamento", "parliament", "noun", "parliament hall assembly seats debate"],
  ["senado", "senate", "noun", "senate chamber debate seats podium"],
  ["congreso", "congress", "noun", "capital congress dome building flags"],
  ["diplomacia", "diplomacy", "noun", "diplomats shaking hands agreement flags"],
  ["embajada", "embassy", "noun", "embassy building flags national seal"],
  ["tratado", "treaty", "noun", "signing international treaty document pen"],
  ["alianza", "alliance", "noun", "corporate strategic alliance handshake"],
  ["coalición", "coalition", "noun", "party coalition leaders shaking hands"],
  ["sindicato", "trade union", "noun", "union rally workers holding hands"],
  ["manifestación", "public demonstration", "noun", "peaceful city march protest rally"],
  ["revolución", "revolution", "noun", "historic crowd movement monument flag"],
  ["independencia", "independence", "noun", "independence day fireworks celebration"],
  ["patriotismo", "patriotism", "noun", "saluting national flag pride respect"],
  ["nacionalismo", "nationalism", "noun", "waving national flag crowd celebration"],
  ["identidad", "identity", "noun", "fingerprint biometric security identity"],
  ["personalidad", "personality", "noun", "human face expressions diverse portraits"],
  ["carácter", "character / nature", "noun", "confident person posture mountain peak"],
  ["temperamento", "temperament", "noun", "artistic expressive face mood painting"],
  ["conducta", "conduct / behavior", "noun", "honest business handshake ethical conduct"],
  ["comportamiento", "behavior", "noun", "observing child behavior playing garden"],
  ["ética", "ethics", "noun", "scales of justice business ethics balance"],
  ["moral", "morals / morality", "noun", "helping hand moral support kindness"],
  ["actitud", "attitude", "noun", "confident athlete ready start track"],
  ["motivación", "motivation", "noun", "climber raising arms mountain peak"],
  ["inspiración", "inspiration", "noun", "artist painting sunrise canvas ocean"],
  ["creatividad", "creativity", "noun", "colorful paint splash art studio"],
  ["imaginación", "imagination", "noun", "child wearing superhero cape flying"],
  ["curiosidad", "curiosity", "noun", "child looking through magnifying glass nature"],
  ["sabiduría", "wisdom", "noun", "wise elderly teacher reading old book"],
  ["inteligencia", "intelligence", "noun", "glowing brain synapse connections idea"],
  ["conciencia", "consciousness / awareness", "noun", "meditating person sunrise peaceful beach"],
  ["espiritualidad", "spirituality", "noun", "zen stones balanced water sunset"],
  ["existencia", "existence", "noun", "person contemplating starry night sky"],
  ["destino", "destiny / fate", "noun", "pathway sun rising over mountains"],
  ["azar", "chance / luck", "noun", "rolling dice game table luck"],
  ["casualidad", "coincidence", "noun", "two matching puzzle pieces fitting"],
  ["probabilidad", "probability", "noun", "probability percentage chart data"],
  ["certidumbre", "certainty", "noun", "solid anchor ocean sea security"],
  ["duda", "doubt / hesitation", "noun", "person looking at crossroad signs choice"],
  ["incertidumbre", "uncertainty", "noun", "foggy road horizon decision path"],
  ["riesgo", "venture / risk", "noun", "rock climber hanging cliff edge risk"],
  ["amenaza", "threat", "noun", "dark storm clouds coming ocean coast"],
  ["desafío", "challenge", "noun", "mountain climber tackling steep ridge"],
  ["reto", "challenge / trial", "noun", "marathon runner approaching finish line"],
  ["obstáculo", "obstacle", "noun", "runner hurdling obstacle track sport"],
  ["dificultad", "difficulty", "noun", "climbing steep rock wall difficulty"],
  ["adversidad", "adversity", "noun", "sprout growing out of dry cracked soil"],
  ["resiliencia", "resilience", "noun", "green tree standing strong in storm"],
  ["superación", "self-improvement", "noun", "person standing victorious mountain peak"],
  ["progreso", "progress", "noun", "stairway leading up to glowing sky"],
  ["evolución", "evolution", "noun", "human evolution timeline illustration"],
  ["transformación", "transformation", "noun", "butterfly emerging from cocoon sprout"],
  ["cambio", "metamorphosis", "noun", "autumn tree changing leaf colors"],
  ["impacto", "impact", "noun", "meteorite crater impact crater space"],
  ["repercusión", "repercussion", "noun", "water ripple effect pond concentric"],
  ["influencia", "influence", "noun", "leader addressing crowd podium inspiring"],
  ["prestigio", "prestige / reputation", "noun", "golden crest medal prestige luxury"],
  ["reputación", "reputation", "noun", "five star gold review rating seal"],
  ["honor", "honor / dignity", "noun", "military medal honor ribbon gold"],
  ["dignidad", "dignity", "noun", "proud person standing tall horizon sun"],
  ["virtud", "virtue", "noun", "white lily flower purity virtue garden"],
  ["mérito", "merit / achievement", "noun", "trophy medal achievement certificate"],
  ["logro", "achievement / accomplishment", "noun", "graduation cap raised diploma diploma"],
  ["hazaña", "feat / deed", "noun", "heroic mountaineer summit flag peak"],
  ["triunfo", "triumph", "noun", "victory parade confetti stadium win"],
  ["éxito", "prosperity", "noun", "growing money tree coins green field"],
  ["prosperidad", "prosperity", "noun", "abundant golden wheat harvest farm"],
  ["riqueza", "wealth", "noun", "golden coins treasure chest vault"],
  ["abundancia", "abundance", "noun", "fruit cornucopia abundant harvest table"],
  ["escasez", "scarcity / shortage", "noun", "dry desert soil drought cracked ground"],
  ["pobreza", "poverty", "noun", "helping hand food aid community charity"],
  ["desigualdad", "inequality", "noun", "unbalanced scales of justice inequality"],
  ["injusticia", "injustice", "noun", "broken gavel courtroom table justice"],
  ["corrupción", "corruption", "noun", "bribe cash envelope briefcase dark"],
  ["transparencia", "transparency", "noun", "clear crystal glass water light"],
  ["honestidad", "honesty", "noun", "honest handshake business trust deal"],
  ["integridad", "integrity", "noun", "solid marble pillar integrity building"],
  ["solidaridad", "humanitarian aid", "noun", "volunteers delivering aid boxes disaster"],
  ["caridad", "charity", "noun", "dropping coins donation box charity"],
  ["filantropía", "philanthropy", "noun", "philanthropist signing donation check foundation"],
  ["voluntariado", "volunteering", "noun", "volunteers planting green trees forest"],
  ["compromiso", "engagement / pledge", "noun", "two hands clasped together pledge"],
  ["deber", "duty", "noun", "soldier standing guard flag duty"],
  ["obligación", "obligation", "noun", "signing legal obligation document pen"],
  ["responsabilidad", "responsibility", "noun", "steering wheel holding hands driver"],
  ["autonomía", "autonomy", "noun", "soaring bird sky freedom flight"],
  ["independencia", "self-reliance", "noun", "hiker walking solo mountain trail"],
  ["libertad", "liberty", "noun", "statue of liberty torch sky"],
  ["soberanía", "national rule", "noun", "parliament building national flag flying"],
  ["autoridad", "authority", "noun", "gavel judge bench courtroom authority"],
  ["poder", "power", "noun", "lightning bolt storm sky power"],
  ["influencia", "clout", "noun", "digital media influencer broadcasting mic"],
  ["liderazgo", "guidance", "noun", "compass lighthouse guiding ship night"],
  ["estrategia", "masterplan", "noun", "architect blueprint drafting table"],
  ["táctica", "tactic", "noun", "soccer coach whiteboard tactics board"],
  ["plan", "scheme / plan", "noun", "calendar schedule project plan desk"],
  ["propuesta", "proposal", "noun", "business presentation slides pitch desk"],
  ["proyecto", "enterprise", "noun", "team reviewing architectural blueprint model"],
  ["iniciativa", "initiative", "noun", "sprout planted in soil green hands"],
  ["inversión", "capital investment", "noun", "growing green plant coins investment"],
  ["financiación", "financing", "noun", "banking loan agreement documents pen"],
  ["subvención", "subsidy / grant", "noun", "grant check certificate research funding"],
  ["presupuesto", "financial budget", "noun", "budget sheet calculation coins pen"],
  ["gastos", "expenses", "noun", "calculating monthly expense receipts table"],
  ["ingresos", "income / revenue", "noun", "rising chart green arrow money revenue"],
  ["ganancias", "earnings", "noun", "handful of gold coins earnings"],
  ["beneficio", "benefit / profit", "noun", "sprouting plant money coins profit"],
  ["rendimiento", "return / yield", "noun", "wheat field golden harvest yield"],
  ["dividendo", "dividend", "noun", "financial growth chart dividend payout"],
  ["acciones", "shares / stocks", "noun", "stock market exchange tickers board"],
  ["bolsa", "stock market", "noun", "wall street stock exchange floor traders"],
  ["inversor", "investor", "noun", "investor reviewing market graph tablet"],
  ["accionista", "shareholder", "noun", "shareholder meeting voting room desk"],
  ["socio", "partner", "noun", "business partners shaking hands agreement"],
  ["aliado", "ally", "noun", "two allies shaking hands flags"],
  ["rival", "competitor", "noun", "athletes running track race competition"],
  ["competidor", "market rival", "noun", "two runners sprinting finish line track"],
  ["cliente", "patron", "noun", "happy client smiling restaurant desk"],
  ["consumidor", "consumer", "noun", "shopper selecting products store aisle"],
  ["usuario", "user", "noun", "person using smartphone digital app"],
  ["suscriptor", "subscriber", "noun", "subscribing digital newsletter tablet click"],
  ["público", "public / audience", "noun", "cheering audience theater concert hall"],
  ["audiencia", "audience", "noun", "spectators in auditorium stadium applause"],
  ["espectador", "viewer / spectator", "noun", "viewers watching movie cinema screen"],
  ["oyente", "listener", "noun", "person listening radio headphones cozy"],
  ["lector", "reader", "noun", "person reading book library cozy chair"],
  ["autor", "author / writer", "noun", "writer typing novel laptop desk"],
  ["creador", "creator", "noun", "digital content creator camera studio"],
  ["artista", "artist", "noun", "painter color palette canvas easel"],
  ["músico", "musician", "noun", "guitarist playing acoustic guitar stage"],
  ["escritor", "writer", "noun", "vintage typewriter writing paper pages"],
  ["pensador", "thinker", "noun", "rodin thinker statue sunset reflection"],
  ["investigador", "researcher", "noun", "researcher looking microscope laboratory"],
  ["científico", "scientist", "noun", "chemist holding lab flask experiment"],
  ["experto", "expert / specialist", "noun", "specialist analyzing data charts desk"],
  ["especialista", "specialist", "noun", "doctor specialist examining patient scan"],
  ["profesional", "professional", "noun", "business professional laptop desk office"],
  ["técnico", "technician", "noun", "technician repairing server circuit board"],
  ["ingeniero", "structural engineer", "noun", "engineer inspecting construction bridge helmet"],
  ["arquitecto", "master architect", "noun", "architect inspecting skyscraper building model"],
  ["diseñador", "designer", "noun", "graphic designer tablet drawing stylus"],
  ["desarrollador", "developer", "noun", "software developer coding two monitors"],
  ["programador", "coder / programmer", "noun", "programmer typing code screen night"],
  ["administrador", "administrator", "noun", "sysadmin managing server rack network"]
];

function buildEntries(arr, level) {
  return arr.map(item => {
    lastId += 1;
    return {
      id: lastId,
      spanish: item[0],
      english: item[1],
      level: level,
      partOfSpeech: item[2],
      imageQuery: item[3],
      image: {
        enabled: true,
        source: "pexels",
        url: null,
        photographer: null,
        photographerUrl: null,
        pexelsUrl: null
      }
    };
  });
}

const newA1 = buildEntries(a1_words, 'A1');
const newA2 = buildEntries(a2_words, 'A2');
const newB1 = buildEntries(b1_words, 'B1');
const newB2 = buildEntries(b2_words, 'B2');

const allWords = [...existingWords, ...newA1, ...newA2, ...newB1, ...newB2];

fs.writeFileSync('data/words.json', JSON.stringify(allWords, null, 2), 'utf-8');

const csvHeader = "id,spanish,english,level,partOfSpeech,imageQuery\n";
const csvRows = allWords.map(w => `${w.id},"${w.spanish}","${w.english}",${w.level},${w.partOfSpeech},"${w.imageQuery}"`).join("\n");

fs.writeFileSync('data/vocab_2000.csv', csvHeader + csvRows, 'utf-8');
fs.writeFileSync('data/vocab_1200.csv', csvHeader + csvRows, 'utf-8'); // Update existing export file too

console.log(`Successfully expanded words dataset! Added: A1=${newA1.length}, A2=${newA2.length}, B1=${newB1.length}, B2=${newB2.length}. Total words: ${allWords.length}.`);
