const fs = require('fs');

const b1_sentences_raw = [
  ["Es importante cuidar el medio ambiente para el futuro.", "It is important to care for the environment for the future.", "green environment nature sprout"],
  ["La investigación científica requiere mucho esfuerzo y paciencia.", "Scientific research requires a lot of effort and patience.", "scientist laboratory research microscope"],
  ["La tecnología moderna cambia nuestra vida cotidiana.", "Modern technology changes our daily life.", "modern technology circuit smartphone"],
  ["Debemos trabajar juntos para mejorar nuestra sociedad.", "We must work together to improve our society.", "diverse group people community"],
  ["La educación es la clave para el desarrollo personal.", "Education is the key to personal development.", "university graduation students"],
  ["El gobierno anunció nuevas medidas para la economía.", "The government announced new measures for the economy.", "parliament building announcement"],
  ["La industria local produce mercancías de alta calidad.", "Local industry produces high quality merchandise.", "factory industrial production"],
  ["Firmamos un contrato de trabajo la semana pasada.", "We signed an employment contract last week.", "signing business contract document"],
  ["El proyecto fue un gran éxito para toda la empresa.", "The project was a great success for the whole company.", "team celebrating project success"],
  ["Debemos definir nuestra estrategia antes de empezar.", "We must define our strategy before starting.", "chess strategy game pieces"],
  ["Encontramos una solución creativa para el problema.", "We found a creative solution for the problem.", "puzzle piece fitting solution"],
  ["El riesgo de la inversión es bastante bajo.", "The investment risk is quite low.", "growing plant coins investment"],
  ["La vacunación ayuda a prevenir enfermedades graves.", "Vaccination helps prevent serious diseases.", "syringe vaccine bottle medical"],
  ["El médico recomendó un tratamiento adecuado.", "The doctor recommended an appropriate treatment.", "doctor consulting patient clinic"],
  ["Valoro mucho la opinión de mis mejores amigos.", "I greatly value the opinion of my best friends.", "two friends talking advice"],
  ["El conocimiento nos da libertad y confianza.", "Knowledge gives us freedom and confidence.", "glowing lightbulb brain idea"],
  ["Con esfuerzo y dedicación alcanzaremos nuestros objetivos.", "With effort and dedication we will achieve our goals.", "climber mountain summit target"],
  ["Sentí una gran alegría al recibir la buena noticia.", "I felt great joy upon receiving the good news.", "happy person jumping joy"],
  ["La esperanza nos ayuda a superar momentos difíciles.", "Hope helps us overcome difficult moments.", "holding glowing light hope"],
  ["Es fundamental mantener la confianza en la pareja.", "It is essential to maintain trust in the relationship.", "couple holding hands trust"],
  ["Los vecinos se unieron para mejorar la comunidad.", "Neighbors joined together to improve the community.", "community garden neighbors working"],
  ["El ciudadano tiene el derecho de votar libremente.", "The citizen has the right to vote freely.", "person voting ballot box"],
  ["El juez dictó la sentencia según la ley.", "The judge handed down the sentence according to the law.", "gavel judge courtroom"],
  ["El abogado presentó pruebas convincentes.", "The lawyer presented convincing proof.", "lawyer presenting evidence court"],
  ["Llegamos a un acuerdo satisfactorio para ambas partes.", "We reached a satisfactory agreement for both parties.", "business handshake deal"],
  ["La paz es necesaria para el progreso social.", "Peace is necessary for social progress.", "white dove flying peace"],
  ["El ejército protegió la frontera nacional.", "The army protected the national border.", "soldiers border checkpoint"],
  ["Es fascinante aprender un idioma extranjero.", "It is fascinating to learn a foreign language.", "world map languages learning"],
  ["Las redes sociales facilitan la comunicación global.", "Social media facilitates global communication.", "social media icons phone"],
  ["La literatura clásica refleja la historia humana.", "Classic literature reflects human history.", "antique book library reading"],
  ["El desarrollo sostenible es una meta mundial.", "Sustainable development is a global goal.", "green planet earth care"],
  ["La investigación médica descubrió una nueva cura.", "Medical research discovered a new cure.", "microscope laboratory science"],
  ["El desempleo disminuyó en el último año.", "Unemployment decreased in the last year.", "rising employment chart graph"],
  ["Presenté una propuesta para el nuevo negocio.", "I presented a proposal for the new business.", "business meeting presentation"],
  ["El presupuesto anual cubre todos los gastos.", "The annual budget covers all expenses.", "financial budget planning calculator"],
  ["Pagamos los impuestos a tiempo cada año.", "We pay taxes on time every year.", "tax form coins calculator"],
  ["El salario mínimo aumentó recientemente.", "The minimum wage increased recently.", "paycheck cash money envelope"],
  ["La seguridad ciudadana es la prioridad local.", "Public security is the local priority.", "police officer neighborhood shield"],
  ["El síntoma principal era la fiebre alta.", "The main symptom was high fever.", "thermometer fever check patient"],
  ["Compré los medicamentos en la farmacia.", "I bought the medicines at the pharmacy.", "pharmacy counter medicine box"],
  ["El consejo del profesor me ayudó mucho.", "The teacher's advice helped me a lot.", "teacher advising student desk"],
  ["La memoria mejora con la práctica diaria.", "Memory improves with daily practice.", "brain memory exercise thought"],
  ["Expresó sus sentimientos con total sinceridad.", "He expressed his feelings with total sincerity.", "person speaking heart sincerely"],
  ["El orgullo de conseguir el título fue enorme.", "The pride of getting the degree was huge.", "graduate student medal diploma"],
  ["Debemos mostrar respeto por la diversidad cultural.", "We must show respect for cultural diversity.", "multicultural group smiling unity"],
  ["La relación entre ambas empresas es excelente.", "The relationship between both companies is excellent.", "corporate partnership handshake"],
  ["El matrimonio celebró su aniversario de bodas.", "The married couple celebrated their wedding anniversary.", "wedding rings couple cake"],
  ["La justicia debe ser igual para todos.", "Justice must be equal for everyone.", "scales of justice gavel court"],
  ["El testigo declaró la verdad en el juicio.", "The witness declared the truth in the trial.", "courtroom witness stand oath"],
  ["Resolvieron la discusión con diálogo tranquilo.", "They resolved the argument with calm dialogue.", "two people talking calmly"],
  ["El anuncio publicitario llamó mi atención.", "The advertisement caught my attention.", "city billboard advertisement"],
  ["La noticia se difundió en la televisión.", "The news was broadcast on television.", "news reporter broadcast tv"],
  ["Leí un poema emotivo en la reunión.", "I read an emotional poem at the meeting.", "poetry manuscript fountain pen"],
  ["La historia antigua revela secretos fascinantes.", "Ancient history reveals fascinating secrets.", "ancient ruins colosseum rome"],
  ["El riesgo de la inversión se puede controlar.", "Investment risk can be controlled.", "financial risk chart shield"],
  ["La empresa invirtió en nuevas tecnologías.", "The company invested in new technologies.", "tech startup glowing circuit"],
  ["Firmaron el contrato de alquiler por un año.", "They signed the lease contract for one year.", "signing apartment lease key"],
  ["El objetivo principal es reducir costos.", "The main objective is to reduce costs.", "target archery bullseye arrow"],
  ["Evaluamos los resultados del experimento.", "We evaluated the results of the experiment.", "science laboratory data chart"],
  ["El fracaso nos enseña lecciones valiosas.", "Failure teaches us valuable lessons.", "person learning from mistake"],
  ["Aprovechó la oportunidad para viajar.", "He took the opportunity to travel.", "open door luggage travel"],
  ["El tratamiento médico fue muy efectivo.", "The medical treatment was very effective.", "doctor healing patient hands"],
  ["La paciencia es necesaria para aprender.", "Patience is necessary for learning.", "zen stones stack patience"],
  ["El sentimiento de empatía nos une.", "The feeling of empathy unites us.", "helping hands support empathy"],
  ["Mantuvo la esperanza hasta el final.", "He kept hope until the end.", "sunrise shining hopeful horizon"],
  ["La vergüenza le impidió hablar en público.", "Shame prevented him from speaking in public.", "person blushing shy expression"],
  ["La amistad verdadera dura toda la vida.", "True friendship lasts a lifetime.", "best friends embracing smiling"],
  ["La comunidad celebró la fiesta patronal.", "The community celebrated the patron saint festival.", "town festival square lights"],
  ["El delito fue investigado por la policía.", "The crime was investigated by the police.", "detective investigating crime scene"],
  ["El acusado contrató a un buen abogado.", "The accused hired a good lawyer.", "lawyer briefcase courtroom"],
  ["La verdad siempre sale a la luz.", "The truth always comes to light.", "sunlight breaking dark clouds"],
  ["La discusión terminó en un abrazo.", "The argument ended in a hug.", "two people reconciling hug"],
  ["La paz duradera requiere entendimiento.", "Lasting peace requires understanding.", "white dove blue sky peace"],
  ["La bandera flameaba en el edificio.", "The flag was waving on the building.", "national flag flying sky"],
  ["El extranjero solicitó la visado de trabajo.", "The foreigner applied for a work visa.", "traveler passport visa office"],
  ["El traductor convirtió el texto al español.", "The translator converted the text to Spanish.", "translator writing dictionary"],
  ["El anuncio en la radio informó del evento.", "The radio announcement informed about the event.", "vintage radio studio mic"],
  ["El cineasta presentó su nueva película.", "The filmmaker presented his new movie.", "movie director camera stage"],
  ["El poeta publicó su primer libro de versos.", "The poet published his first poetry book.", "poet writing feather pen"],
  ["La arquitectura de la ciudad es soberbia.", "The architecture of the city is superb.", "historic architecture cathedral"],
  ["El medio ambiente necesita nuestra protección.", "The environment needs our protection.", "hands holding green sprout"],
  ["El análisis de datos mostró sorpresas.", "Data analysis showed surprises.", "data analytics dashboard graph"],
  ["El salario cubría todos sus gastos mensuales.", "The salary covered all his monthly expenses.", "calculating budget paycheck"],
  ["El síntoma desapareció tras tomar la medicina.", "The symptom disappeared after taking medicine.", "healthy happy patient bed"],
  ["La experiencia laboral es muy importante.", "Work experience is very important.", "resume work history review"],
  ["El esfuerzo diario trae grandes frutos.", "Daily effort yields great fruits.", "gardener harvesting fresh vegetables"],
  ["El miedo no debe paralizar nuestros sueños.", "Fear should not paralyze our dreams.", "person standing brave summit"],
  ["El respeto mutuo fortalece las relaciones.", "Mutual respect strengthens relationships.", "respectful handshake partners"],
  ["La relación comercial fue muy próspera.", "The commercial relationship was very prosperous.", "business partners meeting room"],
  ["El ciudadano ejerció su derecho al voto.", "The citizen exercised his right to vote.", "voter ballot box democracy"],
  ["La ley protege a todos los ciudadanos.", "The law protects all citizens.", "statue of justice scales"],
  ["El testigo prometió decir la verdad.", "The witness promised to tell the truth.", "witness stand oath court"],
  ["Llegaron a un acuerdo tras horas de reunión.", "They reached an agreement after hours of meeting.", "business deal handshake coffee"],
  ["El idioma facilita el intercambio cultural.", "Language facilitates cultural exchange.", "multicultural dialogue speech"],
  ["Las redes sociales conectan a las personas.", "Social media connects people.", "global network social icons"],
  ["La obra de teatro tuvo buenas críticas.", "The play received good reviews.", "theater stage applause audience"],
  ["El autor firmó ejemplares de su libro.", "The author signed copies of his book.", "author signing book fans"],
  ["La tecnología impulsa la innovación.", "Technology drives innovation.", "futuristic glowing circuit lightbulb"],
  ["La sociedad evoluciona constantemente.", "Society evolves constantly.", "city street busy people"],
  ["El contrato establece todas las condiciones.", "The contract specifies all conditions.", "legal contract document pen"],
  ["La estrategia comercial fue acertada.", "The commercial strategy was successful.", "chess strategy board win"],
  ["La vacuna previno el contagio.", "The vaccine prevented contagion.", "syringe vaccine bottle science"],
  ["El consejo de mi abuelo fue sabio.", "My grandfather's advice was wise.", "wise grandfather talking grandchild"],
  ["La emoción al ganar el premio fue enorme.", "The emotion upon winning the award was huge.", "champion trophy celebration"],
  ["La amistad requiere sinceridad y confianza.", "Friendship requires sincerity and trust.", "friends laughing park bench"],
  ["El divorcio fue acordado amistosamente.", "The divorce was agreed upon amicably.", "signing legal papers amicably"],
  ["El policía dirigió el tráfico denso.", "The police officer directed the heavy traffic.", "police officer traffic intersection"],
  ["El abogado defendió al cliente con pasión.", "The lawyer defended the client with passion.", "lawyer speaking courtroom jury"],
  ["El conflicto fue solucionado pacíficamente.", "The conflict was solved peacefully.", "shaking hands peace agreement"],
  ["La frontera separa los dos países.", "The border separates the two countries.", "border river bridge crossing"],
  ["La traducción del documento fue precisa.", "The translation of the document was precise.", "translation dictionary document"],
  ["La televisión retransmitió el partido.", "Television broadcasted the match.", "live sports tv broadcast"],
  ["La historia nos enseña los errores del pasado.", "History teaches us past mistakes.", "ancient museum artifacts history"],
  ["El medio ambiente requiere atención urgente.", "The environment requires urgent attention.", "protecting earth nature hands"],
  ["El proyecto avanza según lo planificado.", "The project progresses as planned.", "blueprint project plan meeting"],
  ["La inversión trajo excelentes beneficios.", "The investment brought excellent profits.", "sprouting plant money coins"],
  ["El tratamiento médico fue un éxito total.", "The medical treatment was a complete success.", "healthy patient leaving hospital"],
  ["La memoria nos permite recordar bellos momentos.", "Memory allows us to recall beautiful moments.", "cherished family photo album"],
  ["El respeto por los mayores es fundamental.", "Respect for elders is fundamental.", "young person helping elder"],
  ["La comunidad organizó una limpieza del parque.", "The community organized a park cleanup.", "volunteers cleaning green park"],
  ["El juez escuchó atentamente a ambas partes.", "The judge listened attentively to both sides.", "judge courtroom listening gavel"],
  ["Llegamos a un acuerdo beneficioso.", "We reached a beneficial agreement.", "handshake corporate deal"],
  ["El idioma oficial es el español.", "The official language is Spanish.", "spanish dictionary textbook"],
  ["La televisión informó sobre el clima.", "Television reported on the weather.", "weather forecast tv screen"],
  ["La historia de la ciencia es fascinante.", "The history of science is fascinating.", "vintage scientific instruments"],
  ["La estrategia redujo los costos.", "The strategy reduced costs.", "cost reduction chart graph"],
  ["La vacuna protegió a la población.", "The vaccine protected the population.", "medical immunization syringe"],
  ["La emoción embargó al ganador.", "Emotion overwhelmed the winner.", "tearful joyful winner trophy"],
  ["El matrimonio celebró sus bodas de oro.", "The married couple celebrated golden wedding.", "elderly couple anniversary cake"],
  ["El abogado redactó el contrato final.", "The lawyer drafted the final contract.", "lawyer pen writing contract"],
  ["La paz trajo prosperidad a la región.", "Peace brought prosperity to the region.", "peaceful sunny valley town"],
  ["La traducción fue publicada en varios idiomas.", "The translation was published in several languages.", "multilingual books stack"],
  ["El museo alberga obras famosas.", "The museum houses famous works.", "art museum gallery paintings"],
  ["El desarrollo económico beneficia a todos.", "Economic development benefits everyone.", "modern city skyline growth"],
  ["La inversión generó miles de empleos.", "The investment generated thousands of jobs.", "new factory workers job"],
  ["La experiencia nos ayuda a tomar decisiones.", "Experience helps us make decisions.", "wise leader making decision"],
  ["El orgullo de nuestra cultura es grande.", "The pride of our culture is great.", "traditional cultural festival dance"],
  ["La ley garantiza la libertad de prensa.", "The law guarantees freedom of the press.", "newspaper printing press machine"],
  ["El conflicto se resolvió mediante diálogo.", "The conflict was resolved through dialogue.", "peaceful dialogue round table"],
  ["Las noticias de la mañana fueron positivas.", "Morning news was positive.", "newspaper headlines coffee"],
  ["La investigación espacial avanza rápido.", "Space research advances quickly.", "space telescope galaxy stars"],
  ["El salario permite vivir con comodidad.", "The salary allows living comfortably.", "cozy apartment home living"],
  ["La relación cliente empresa es primordial.", "Client company relationship is essential.", "happy client customer handshake"],
  ["El juez aplazó la sesión del juicio.", "The judge adjourned the trial session.", "gavel courtroom judge desk"],
  ["El idioma nos permite conectar emociones.", "Language allows us to connect emotions.", "heart speech bubbles dialogue"],
  ["La historia del arte inspira a los pintores.", "Art history inspires painters.", "artist painting outdoor canvas"],
  ["La seguridad informática protege nuestros datos.", "IT security protects our data.", "cyber security digital lock"],
  ["La experiencia adquirida fue inestimable.", "The experience gained was invaluable.", "climbing mountain peak achievement"],
  ["El respeto abre muchas puertas en la vida.", "Respect opens many doors in life.", "open door golden light"],
  ["El contrato incluye seguro de salud.", "The contract includes health insurance.", "health insurance document shield"],
  ["La vacuna se distribuyó en todo el país.", "The vaccine was distributed nationwide.", "medical transport vaccine boxes"],
  ["La emoción de viajar nos alegra.", "The excitement of traveling pleases us.", "traveler airport boarding plane"],
  ["El policía recibió una medalla al honor.", "The police officer received a medal of honor.", "police medal honor ceremony"],
  ["La paz es el camino hacia el futuro.", "Peace is the way to the future.", "sun rising over peaceful valley"],
  ["El museo abre todos los días excepto lunes.", "The museum opens every day except Monday.", "museum entrance opening hours"],
  ["El proyecto recibió financiación internacional.", "The project received international funding.", "global funding piggy bank"],
  ["La experiencia nos enseña a ser mejores.", "Experience teaches us to be better.", "reading book wise thoughts"],
  ["La comunidad celebró la inauguración.", "The community celebrated the inauguration.", "ribbon cutting ceremony inauguration"],
  ["El abogado presentó el recurso judicial.", "The lawyer submitted the judicial appeal.", "legal appeal documents court"],
  ["La historia es la maestra de la vida.", "History is the teacher of life.", "classic history library books"],
  ["La inversión impulsó el comercio local.", "Investment boosted local commerce.", "busy local market shops"],
  ["El respeto a las opiniones ajenas es esencial.", "Respect for others' opinions is essential.", "respectful debate round table"],
  ["El contrato fue firmado por ambas partes.", "The contract was signed by both parties.", "signing business agreement pen"],
  ["La paz reina en la pequeña aldea.", "Peace reigns in the small village.", "serene mountain village sunset"],
  ["El museo ofrece visitas guiadas gratis.", "The museum offers free guided tours.", "museum tour guide visitors"],
  ["El proyecto finalizó con gran éxito.", "The project finished with great success.", "team celebrating completion project"],
  ["La experiencia fue verdaderamente inolvidable.", "The experience was truly unforgettable.", "hot air balloon sunset flight"],
  ["La ley apoya la protección de la naturaleza.", "The law supports nature protection.", "forester planting green tree"],
  ["La historia continúa en el siguiente capítulo.", "History continues in the next chapter.", "turning page book reading"]
];

// Load existing sentences
const rawExistingSentences = JSON.parse(fs.readFileSync('data/sentences.json', 'utf-8'));

const added_sentences = b1_sentences_raw.map((item, idx) => {
  const id = 9402 + idx;
  return {
    id,
    spanish: item[0],
    english: item[1],
    level: "B1",
    partOfSpeech: "phrase",
    imageQuery: item[2],
    image: {
      enabled: true,
      source: "pexels",
      url: null,
      photographer: null,
      photographerUrl: null,
      pexelsUrl: null
    }
  };
});

const all_sentences = [...rawExistingSentences, ...added_sentences];

fs.writeFileSync('data/sentences.json', JSON.stringify(all_sentences, null, 2), 'utf-8');

const csvHeader = "id,spanish,english,level,partOfSpeech,imageQuery\n";
const csvRows = all_sentences.map(s => `${s.id},"${s.spanish}","${s.english}",${s.level},${s.partOfSpeech},"${s.imageQuery}"`).join("\n");

fs.writeFileSync('data/sentences_600.csv', csvHeader + csvRows, 'utf-8');

console.log(`Successfully added ${added_sentences.length} B1 sentences! Total sentences dataset: ${all_sentences.length}.`);
