const fs = require('fs');

const a2_sentences_raw = [
  ["Me acuesto temprano todas las noches.", "I go to bed early every night.", "person going bed night"],
  ["Se levanta a las siete de la mañana.", "He gets up at seven in the morning.", "person getting out bed morning"],
  ["Nos duchamos después de hacer ejercicio.", "We shower after exercising.", "shower water stream"],
  ["Ellos se bañan en el lago limpio.", "They take a bath in the clean lake.", "swimming clean lake"],
  ["Me visto con una camisa azul y pantalones.", "I get dressed in a blue shirt and pants.", "person dressing shirt outfit"],
  ["Ella se peina frente al espejo.", "She combs her hair in front of the mirror.", "woman combing hair mirror"],
  ["Mi hermano se afeita cada mañana.", "My brother shaves every morning.", "man shaving beard mirror"],
  ["Se maquilla antes de salir a la fiesta.", "She puts on makeup before going out to the party.", "woman applying makeup"],
  ["Me despierto con el sonido del reloj.", "I wake up with the sound of the alarm.", "alarm clock waking up"],
  ["El niño se duerme rápido.", "The child falls asleep quickly.", "child sleeping cozy bed"],
  ["Por favor, siéntate en esta silla.", "Please, sit down in this chair.", "sitting armchair comfortable"],
  ["Nos levantamos para saludar al profesor.", "We stand up to greet the teacher.", "students standing greeting"],
  ["Prefiero quedarme en casa este fin de semana.", "I prefer to stay at home this weekend.", "cozy house living room"],
  ["Ellos se van mañana por la mañana.", "They are leaving tomorrow morning.", "travelers leaving airport suitcases"],
  ["No me acuerdo de su nombre.", "I do not remember his name.", "person trying remember thought"],
  ["Se enfermó durante el viaje de vacaciones.", "He fell sick during the vacation trip.", "sick person hotel bed"],
  ["El médico ayuda a curar al paciente.", "The doctor helps heal the patient.", "doctor examining patient clinic"],
  ["Él se queja del ruido de la calle.", "He complains about the street noise.", "annoyed person hands on ears"],
  ["Nos divertimos mucho en el parque.", "We have a lot of fun in the park.", "friends having fun laughing"],
  ["El estudiante se aburre en la clase larga.", "The student gets bored in the long class.", "bored student desk classroom"],
  ["Mi madre se preocupa cuando llego tarde.", "My mother worries when I arrive late.", "mother worried waiting clock"],
  ["Me relajo escuchando música suave.", "I relax listening to soft music.", "person relaxing headphones park"],
  ["El corredor se cansa después de diez kilómetros.", "The runner gets tired after ten kilometers.", "tired runner resting track"],
  ["El gato se asusta con el trueno.", "The cat gets scared of the thunder.", "scared kitten hiding"],
  ["Ellos se enamoraron en la universidad.", "They fell in love in college.", "romantic couple walking park"],
  ["Se casan el próximo mes de junio.", "They are getting married next month in June.", "wedding couple bride groom"],
  ["Nos mudamos a una casa más grande.", "We are moving to a bigger house.", "moving truck boxes house"],
  ["Me acostumbro rápido al nuevo clima.", "I get used to the new climate quickly.", "sunny city street walking"],
  ["Casi todos se equivocan al principio.", "Almost everyone makes a mistake at first.", "person pencil erasing mistake"],
  ["Ella se sorprende con la fiesta secreta.", "She is surprised by the secret party.", "surprised woman party confetti"],
  ["Llegamos al aeropuerto dos horas antes.", "We arrive at the airport two hours early.", "airport departures terminal"],
  ["El tren sale de la estación a las cuatro.", "The train leaves the station at four.", "train departing platform"],
  ["Esperamos el autobús en la parada.", "We wait for the bus at the stop.", "bus stop passengers waiting"],
  ["El barco llega al puerto al atardecer.", "The ship arrives at the harbor at sunset.", "ship harbor sunset"],
  ["Compro un billete de ida y vuelta.", "I buy a round trip ticket.", "travel ticket passport"],
  ["Muestro mi pasaje en la puerta de embarque.", "I show my boarding pass at the gate.", "airline boarding pass ticket"],
  ["Llevamos dos maletas pesadas.", "We carry two heavy suitcases.", "suitcases travel airport"],
  ["Guardo la cámara en mi mochila.", "I keep the camera in my backpack.", "hiking backpack camera"],
  ["Ella lleva un bolso elegante.", "She carries an elegant handbag.", "stylish woman handbag"],
  ["Miramos el mapa para encontrar el museo.", "We look at the map to find the museum.", "tourists reading city map"],
  ["La guía turística explica la historia.", "The tourist guide explains the history.", "tour guide leading group"],
  ["Hacemos una excursión a las montañas.", "We make an excursion to the mountains.", "hikers mountain excursion"],
  ["El vuelo tiene un retraso de una hora.", "The flight has a delay of one hour.", "flight delay board airport"],
  ["La salida es a las cinco de la tarde.", "Departure is at five in the afternoon.", "airport departure sign"],
  ["La llegada se espera a medianoche.", "Arrival is expected at midnight.", "airplane landing night"],
  ["Pasamos por la aduana sin problemas.", "We go through customs without problems.", "airport customs control"],
  ["Tengo que renovar mi pasaporte.", "I have to renew my passport.", "passport book stamps"],
  ["Necesitas un visado para entrar al país.", "You need a visa to enter the country.", "passport visa stamp entry"],
  ["Reservamos una habitación en el hotel.", "We reserve a room in the hotel.", "hotel lobby reception desk"],
  ["Pedimos la llave en la recepción.", "We ask for the key at reception.", "hotel receptionist keycard"],
  ["Queremos una habitación doble con vista.", "We want a double room with a view.", "hotel double bedroom window"],
  ["El ascensor del hotel sube rápido.", "The hotel elevator goes up fast.", "modern hotel elevator hall"],
  ["Los niños nadan en la piscina.", "The children swim in the pool.", "swimming pool resort kids"],
  ["Hago ejercicio en el gimnasio.", "I exercise in the gym.", "gym fitness workout"],
  ["Cenamos en un restaurante italiano.", "We have dinner at an Italian restaurant.", "restaurant table dining pizza"],
  ["El camarero nos trae el menú.", "The waiter brings us the menu.", "waiter bringing menu table"],
  ["Pedimos el menú del día.", "We order the menu of the day.", "restaurant blackboard menu"],
  ["Pedimos la cuenta al final.", "We ask for the bill at the end.", "restaurant receipt check"],
  ["Dejamos una propina generosa.", "We leave a generous tip.", "cash tip table restaurant"],
  ["El plato principal es pescado con patatas.", "The main course is fish with potatoes.", "gourmet fish meal plate"],
  ["De entrada pedimos una ensalada.", "For appetizer we order a salad.", "fresh salad starter plate"],
  ["El postre del día es tarta de queso.", "The dessert of the day is cheesecake.", "cheesecake dessert slice"],
  ["Bebemos zumo de naranja fresco.", "We drink fresh orange juice.", "glass fresh orange juice"],
  ["El vino tinto es muy sabroso.", "The red wine is very tasty.", "glass of red wine bottle"],
  ["Preferimos tomar agua mineral fría.", "We prefer to drink cold mineral water.", "mineral water bottle glass"],
  ["Tomamos café con leche por la mañana.", "We drink coffee with milk in the morning.", "cup latte coffee saucer"],
  ["Pongo dos cubos de hielo en la bebida.", "I put two ice cubes in the drink.", "glass ice cubes beverage"],
  ["El pan fresco huele riquísimo.", "Fresh bread smells delicious.", "loaf fresh bakery bread"],
  ["Servimos sopa caliente en invierno.", "We serve hot soup in winter.", "steaming soup bowl spoon"],
  ["Pedimos una ración de tortilla española.", "We order a portion of Spanish omelette.", "spanish potato omelette slice"],
  ["El queso manchego es bastante famoso.", "Manchego cheese is quite famous.", "manchego cheese wedge grapes"],
  ["Probamos las tapas en el bar.", "We try the tapas at the bar.", "assorted spanish tapas bar"],
  ["Hacemos la compra en el supermercado.", "We do the shopping at the supermarket.", "supermarket shopping cart"],
  ["Compro pantalones en la tienda de ropa.", "I buy pants at the clothing store.", "clothing boutique racks"],
  ["Probamos zapatos en la zapatería.", "We try shoes at the shoe store.", "shoe store display sneakers"],
  ["Compramos pasteles en la panadería.", "We buy pastries at the bakery.", "bakery shop pastries display"],
  ["Compro carne en la carnicería.", "I buy meat at the butcher shop.", "butcher shop fresh meat"],
  ["El pescado fresco está en la pescadería.", "Fresh fish is at the fish market.", "fresh fish market stall"],
  ["Compramos fruta madura en la frutería.", "We buy ripe fruit at the fruit shop.", "fruit store colorful apples"],
  ["La farmacia de guardia abre toda la noche.", "The duty pharmacy opens all night.", "pharmacy green cross night"],
  ["Compro una novela en la librería.", "I buy a novel at the bookstore.", "bookstore bookshelf novels"],
  ["Compramos cuadernos en la papelería.", "We buy notebooks at the stationery shop.", "stationery notebooks pens"],
  ["Paseamos por el centro comercial.", "We stroll through the shopping mall.", "shopping mall interior atrium"],
  ["Saco dinero del cajero automático.", "I withdraw money from the ATM.", "using ATM machine cash"],
  ["Voy al banco a abrir una cuenta.", "I go to the bank to open an account.", "bank entrance office"],
  ["Envío un paquete en la oficina de correos.", "I send a package at the post office.", "post office counter parcel"],
  ["La comisaría está cerca de la plaza.", "The police station is near the square.", "police station car exterior"],
  ["Llevan al enfermo al hospital.", "They take the sick person to the hospital.", "ambulance hospital entrance"],
  ["Tengo una cita en la clínica médica.", "I have an appointment at the medical clinic.", "doctor clinic office desk"],
  ["Voy al dentista una vez al año.", "I go to the dentist once a year.", "dentist exam chair smile"],
  ["El veterinario cura al perro.", "The vet heals the dog.", "veterinarian examining dog"],
  ["Me corto el pelo en la peluquería.", "I get a haircut at the hair salon.", "hairdresser cutting hair salon"],
  ["Arreglan el coche en el taller mecánico.", "They fix the car at the auto repair shop.", "mechanic fixing car engine"],
  ["Llenamos el depósito en la gasolinera.", "We fill the tank at the gas station.", "fueling car gas pump"],
  ["Lavamos las sábanas en la lavandería.", "We wash the bedsheets at the laundromat.", "laundromat washing machines"],
  ["Vemos una película en el cine de verano.", "We watch a movie at the outdoor summer cinema.", "outdoor cinema screen night"],
  ["Compramos entradas para el teatro.", "We buy tickets for the theater.", "theater stage red curtains"],
  ["Admiramos cuadros en el museo de arte.", "We admire paintings in the art museum.", "art museum paintings gallery"],
  ["Estudiamos en la biblioteca pública.", "We study in the public library.", "quiet library study tables"],
  ["Nos montamos en la montaña rusa del parque.", "We ride the roller coaster at the amusement park.", "amusement park roller coaster"],
  ["Vemos animales raros en el zoológico.", "We see rare animals at the zoo.", "zoo giraffes enclosure"],
  ["El estadio de fútbol está lleno.", "The soccer stadium is full.", "packed soccer stadium lights"],
  ["Jugamos al baloncesto en el gimnasio deportivo.", "We play basketball at the sports center.", "indoor basketball court game"],
  ["Jugamos un partido en la pista de tenis.", "We play a match on the tennis court.", "tennis court net match"],
  ["Caminamos por la playa de arena dorada.", "We walk on the golden sandy beach.", "golden sandy beach waves"],
  ["La montaña nevada es imponente.", "The snowy mountain is imposing.", "snowy mountain peak blue sky"],
  ["Cruzamos el bosque verde y frondoso.", "We cross the green and lush forest.", "lush green forest trees path"],
  ["El río caudaloso fluye hacia el mar.", "The rushing river flows towards the sea.", "flowing river mountain valley"],
  ["Navegamos en barco por el lago azul.", "We sail by boat on the blue lake.", "boat blue lake reflection"],
  ["Visitamos una isla tropical en vacaciones.", "We visit a tropical island on vacation.", "tropical island palm beach"],
  ["El sol brilla en el día soleado.", "The sun shines on the sunny day.", "bright sun blue sky day"],
  ["El cielo está totalmente nublado.", "The sky is totally cloudy.", "cloudy dark sky overcast"],
  ["Está lluvioso así que llevo paraguas.", "It is rainy so I carry an umbrella.", "person umbrella rainy street"],
  ["La tormenta trae truenos y relámpagos.", "The storm brings thunder and lightning.", "lightning storm night sky"],
  ["Cae la nieve en las montañas.", "Snow falls in the mountains.", "snow falling winter trees"],
  ["Sopla un viento fuerte hoy.", "A strong wind is blowing today.", "wind blowing trees leaves"],
  ["Hay mucha niebla por la mañana.", "There is a lot of fog in the morning.", "foggy morning road trees"],
  ["La temperatura baja por la noche.", "The temperature drops at night.", "thermometer cold night"],
  ["Hace calor dentro de la casa.", "It is hot inside the house.", "cozy warm sunny room"],
  ["El agua del mar está muy fría.", "The sea water is very cold.", "cold ocean waves beach"],
  ["Disfrutamos del día primaveral.", "We enjoy the spring-like day.", "spring blooming flowers park"],
  ["El ambiente veraniego es alegre.", "The summer-like atmosphere is cheerful.", "beach pool party summer"],
  ["Las hojas otoñales caen al suelo.", "The autumnal leaves fall to the ground.", "autumn leaves park ground"],
  ["El paisaje invernal está blanco.", "The wintry landscape is white.", "snowy wintry trees village"],
  ["Salimos de viaje de madrugada.", "We set off on a trip early in the morning.", "early morning road trip dawn"],
  ["Miramos el atardecer junto al mar.", "We watch the sunset by the sea.", "golden sunset ocean waves"],
  ["El amanecer en la montaña es hermoso.", "Sunrise in the mountains is beautiful.", "mountain peak sunrise dawn"],
  ["Consulto mi horario de clases.", "I check my class schedule.", "student checking timetable schedule"],
  ["Miro la fecha en el calendario.", "I look at the date on the calendar.", "calendar page date circle"],
  ["Miro mi reloj de pulsera.", "I look at my wristwatch.", "wristwatch on wrist time"],
  ["La alarma suena a las seis y media.", "The alarm rings at six thirty.", "alarm clock ringing morning"],
  ["Espérame solo un minuto.", "Wait for me just one minute.", "stopwatch timer minute"],
  ["La carrera dura pocos segundos.", "The race lasts a few seconds.", "digital race timer finish line"],
  ["Llegamos a la hora puntual.", "We arrive at the exact time.", "clock hands exact time"],
  ["Trabajamos durante el día.", "We work during the day.", "bright daytime office work"],
  ["Caminamos por la ciudad por la noche.", "We walk through the city at night.", "city night lights walk"],
  ["El reloj da doce campanadas a medianoche.", "The clock strikes twelve chimes at midnight.", "clock tower striking midnight"],
  ["Llegamos a tiempo para la película.", "We arrive on time for the movie.", "movie theater entrance on time"],
  ["El autobús viene con retraso.", "The bus comes with a delay.", "bus waiting stop clock"],
  ["De repente empezó a llover.", "Suddenly it started to rain.", "sudden rain street umbrella"],
  ["Por fin terminamos el examen.", "At last we finished the exam.", "happy student finishing exam"],
  ["Al principio no entendía la lección.", "At first I did not understand the lesson.", "confused student book desk"],
  ["Al final todos celebramos el éxito.", "In the end we all celebrate the success.", "team celebrating victory win"],
  ["Sin embargo seguimos intentando.", "However we keep trying.", "persistent runner track"],
  ["Por lo tanto aprobamos el curso.", "Therefore we passed the course.", "happy student diploma certificate"],
  ["Además aprendemos muchas cosas.", "Furthermore we learn many things.", "books library learning"],
  ["Yo tampoco lo sabía.", "Neither did I know it.", "two friends nodding agreement"],
  ["Todavía estamos a tiempo.", "We are still on time.", "clock running catching train"],
  ["Ya no vivo en esa calle.", "I no longer live on that street.", "moving away street sign"],
  ["Casi siempre desayuno café.", "I almost always eat breakfast with coffee.", "morning coffee breakfast cup"],
  ["De vez en cuando voy al cine.", "Once in a while I go to the cinema.", "movie theater popcorn seat"],
  ["Pocas veces como comida rápida.", "I rarely eat fast food.", "healthy salad meal plate"],
  ["Buscamos en todas partes.", "We search everywhere.", "searching room everywhere"],
  ["No lo encontré en ninguna parte.", "I did not find it anywhere.", "empty quiet room search"],
  ["Está oculto en algún lugar.", "It is hidden somewhere.", "treasure map hidden spot"],
  ["Caminamos hacia adelante con valor.", "We walk forward with courage.", "hikers walking forward trail"],
  ["Da un paso hacia atrás.", "Take one step backward.", "person stepping backward"],
  ["Gira a la izquierda en el semáforo.", "Turn to the left at the traffic light.", "traffic light turn left sign"],
  ["Dobla a la derecha en la esquina.", "Turn to the right at the corner.", "street corner turn right sign"],
  ["Sigue todo recto por dos manzanas.", "Go straight ahead for two blocks.", "straight highway road sign"],
  ["La farmacia está en la esquina.", "The pharmacy is on the corner.", "street corner pharmacy sign"],
  ["El banco está al lado del museo.", "The bank is next to the museum.", "bank museum buildings side"],
  ["La cafetería está enfrente de la estación.", "The coffee shop is in front of the station.", "cafe in front of station"],
  ["El jardín está detrás de la casa.", "The garden is behind the house.", "backyard garden behind house"],
  ["El gato duerme debajo de la mesa.", "The cat sleeps underneath the table.", "cat sleeping under dining table"],
  ["El libro está encima de la estantería.", "The book is on top of the bookshelf.", "book top of bookshelf"],
  ["La tienda está entre el restaurante y el hotel.", "The shop is between the restaurant and the hotel.", "shop between two buildings"],
  ["Caminamos alrededor del parque.", "We walk around the park.", "people walking around park pond"],
  ["La luz pasa a través de la ventana.", "Light passes through the window.", "sunlight streaming window"],
  ["Es una persona muy amable y atenta.", "She is a very kind and attentive person.", "kind person helping elder"],
  ["Mi nuevo compañero es muy simpático.", "My new classmate is very nice.", "friendly smiling classmate"],
  ["No me gusta la gente antipática.", "I do not like unfriendly people.", "unfriendly frowning person"],
  ["El estudiante inteligente resuelve el problema.", "The intelligent student solves the problem.", "smart student blackboard math"],
  ["Es un perro trabajador y leal.", "He is a hardworking and loyal dog.", "working dog loyal shepherd"],
  ["No seas perezoso y empieza a estudiar.", "Do not be lazy and start studying.", "person studying desk book"],
  ["Es muy generoso con sus amigos.", "He is very generous with his friends.", "sharing food generous friend"],
  ["Una película divertida nos alegra el día.", "A funny movie brightens our day.", "laughing audience movie theater"],
  ["Nos vemos pronto en la cafetería.", "See you soon at the coffee shop.", "friends wave coffee shop"],
  ["Tengo muchas ganas de viajar.", "I really want to travel.", "traveler passport suitcase map"],
  ["El agua de la piscina está templada.", "The pool water is lukewarm.", "warm swimming pool resort"],
  ["Me gusta pasear por la mañana temprano.", "I like to stroll early in the morning.", "early morning peaceful walk"],
  ["Cerraron la tienda antes de tiempo.", "They closed the shop ahead of time.", "closed shop front door"],
  ["Comemos fruta todos los días.", "We eat fruit every day.", "fresh fruit salad bowl"],
  ["El autobús llegó a su hora.", "The bus arrived on schedule.", "bus arriving transit stop"],
  ["Disfrutamos de unas buenas vacaciones.", "We enjoyed a great vacation.", "resort beach holiday lounge"],
  ["El café caliente nos reconforta.", "Hot coffee comforts us.", "mug hot steaming coffee"],
  ["Hacemos planes para el fin de semana.", "We make plans for the weekend.", "planning calendar weekend trip"],
  ["La música suena muy alegre.", "The music sounds very cheerful.", "upbeat music headphones dance"],
  ["Gracias por tu valiosa ayuda.", "Thank you for your valuable help.", "shaking hands thank you"],
  ["Buen viaje a todos.", "Have a good trip everyone.", "waving goodbye airport departure"]
];

// Load existing sentences
const rawExistingSentences = JSON.parse(fs.readFileSync('data/sentences.json', 'utf-8'));

const added_sentences = a2_sentences_raw.map((item, idx) => {
  const id = 9212 + idx;
  return {
    id,
    spanish: item[0],
    english: item[1],
    level: "A2",
    partOfSpeech: "phrase",
    imageQuery: item[2],
    image: {
      enabled: true,
      source: "pexels",
      url: null,
      photographer: null,
      photographerUrl: null,
      pexelsUrl: null
    }
  };
});

const all_sentences = [...rawExistingSentences, ...added_sentences];

fs.writeFileSync('data/sentences.json', JSON.stringify(all_sentences, null, 2), 'utf-8');

const csvHeader = "id,spanish,english,level,partOfSpeech,imageQuery\n";
const csvRows = all_sentences.map(s => `${s.id},"${s.spanish}","${s.english}",${s.level},${s.partOfSpeech},"${s.imageQuery}"`).join("\n");

fs.writeFileSync('data/sentences_400.csv', csvHeader + csvRows, 'utf-8');

console.log(`Successfully added ${added_sentences.length} A2 sentences! Total sentences dataset: ${all_sentences.length}.`);
