const fs = require('fs');

const b2_sentences_raw = [
  ["La arquitectura contemporánea de la ciudad combina innovación y tradición.", "The contemporary architecture of the city combines innovation and tradition.", "modern architecture skyscraper glass"],
  ["La filosofía nos invita a reflexionar sobre el sentido de la existencia.", "Philosophy invites us to reflect on the meaning of existence.", "thinker statue philosophy reflection"],
  ["La psicología estudia el comportamiento humano y los procesos mentales.", "Psychology studies human behavior and mental processes.", "brain puzzle psychology concept"],
  ["La sociología analiza cómo se estructuran y evolucionan las sociedades.", "Sociology analyzes how societies structure and evolve.", "connected people network network"],
  ["La astronomía nos permite explorar los misterios del universo.", "Astronomy allows us to explore the mysteries of the universe.", "stargazing telescope galaxy starry night"],
  ["La biología molecular ha avanzado significativamente en esta década.", "Molecular biology has advanced significantly in this decade.", "dna helix biology laboratory"],
  ["La química orgánica estudia las estructuras y reacciones de los compuestos.", "Organic chemistry studies the structures and reactions of compounds.", "chemistry lab flasks scientist"],
  ["La física cuántica cuestiona nuestra percepción tradicional de la realidad.", "Quantum physics questions our traditional perception of reality.", "atom physics orbit quantum glowing"],
  ["Las matemáticas avanzadas proporcionan la base para la inteligencia artificial.", "Advanced mathematics provides the foundation for artificial intelligence.", "math formulas blackboard study"],
  ["La geometría fractal describe patrones complejos presentes en la naturaleza.", "Fractal geometry describes complex patterns present in nature.", "geometric compass shapes fractal"],
  ["La estadística aplicada nos permite predecir tendencias con precisión.", "Applied statistics allows us to predict trends with precision.", "statistical data graph analysis"],
  ["El algoritmo de recomendación personaliza el contenido para cada usuario.", "The recommendation algorithm personalizes content for each user.", "computer code algorithm screen"],
  ["La inteligencia artificial transforma rápidamente el mercado laboral.", "Artificial intelligence quickly transforms the job market.", "ai robot brain glowing tech"],
  ["La robótica industrial optimiza los procesos de fabricación en fábrica.", "Industrial robotics optimizes manufacturing processes in factories.", "robotic arm factory production"],
  ["La ciberseguridad es vital para proteger la información confidencial.", "Cybersecurity is vital for protecting confidential information.", "digital padlock cyber security shield"],
  ["La transición a energías renovables es imprescindible contra el cambio climático.", "The transition to renewable energy is indispensable against climate change.", "wind turbines solar panels green"],
  ["La sostenibilidad ambiental requiere la colaboración de gobiernos e industrias.", "Environmental sustainability requires collaboration between governments and industries.", "green sprout earth care hands"],
  ["El cambio climático provoca el deshielo acelerado de los glaciares.", "Climate change causes the accelerated melting of glaciers.", "melting glacier iceberg ocean"],
  ["La contaminación atmosférica afecta negativamente a la salud urbana.", "Atmospheric pollution negatively affects urban health.", "smokestack factory smoke sky"],
  ["El reciclaje sistemático reduce drásticamente los residuos industriales.", "Systematic recycling drastically reduces industrial waste.", "green recycling symbol bin"],
  ["La preservación de la biodiversidad es fundamental para el equilibrio ecológico.", "Preserving biodiversity is fundamental for ecological balance.", "coral reef wildlife ocean green"],
  ["Varias especies animales se encuentran actualmente en peligro crítico.", "Several animal species are currently in critical danger.", "wild tiger jungle forest"],
  ["Evitar la extinción masiva de fauna requiere reservas naturales protegidas.", "Avoiding mass wildlife extinction requires protected natural reserves.", "dinosaur fossil museum exhibit"],
  ["La conservación de bosques tropicales ayuda a regular el clima planetario.", "Tropical forest conservation helps regulate planetary climate.", "forest ranger tree planting green"],
  ["La gestión responsable de recursos naturales previene la escasez futura.", "Responsible management of natural resources prevents future scarcity.", "water waterfall forest nature"],
  ["La volatilidad del mercado del petróleo impacta la economía mundial.", "Petroleum market volatility impacts the global economy.", "oil rig ocean platform"],
  ["La infraestructura moderna mejora la conectividad entre regiones distantes.", "Modern infrastructure improves connectivity between distant regions.", "bridge construction highway modern"],
  ["El transporte público eficiente reduce la congestión de tráfico urbano.", "Efficient public transport reduces urban traffic congestion.", "subway metro train station"],
  ["El urbanismo sostenible diseña ciudades pensadas para los peatones.", "Sustainable urban planning designs cities meant for pedestrians.", "futuristic city model green walk"],
  ["El acceso a una vivienda digna es un derecho social fundamental.", "Access to decent housing is a fundamental social right.", "suburban neighborhood houses green"],
  ["Las tasas de interés de la hipoteca influyen en la compra de inmuebles.", "Mortgage interest rates influence property purchases.", "miniature house key contract"],
  ["El precio del alquiler de viviendas ha aumentado en las grandes capitales.", "Housing rent prices have increased in major capitals.", "handing house key lease agreement"],
  ["El patrimonio histórico de la ciudad atrae a visitantes de todo el mundo.", "The historic heritage of the city attracts visitors from all over the world.", "historic castle heritage fortress"],
  ["El turismo responsable promueve el respeto por la cultura local.", "Responsible tourism promotes respect for local culture.", "tourists taking photos monument"],
  ["La gastronomía internacional fusiona sabores tradicionales y vanguardistas.", "International gastronomy fuses traditional and avant-garde flavors.", "gourmet restaurant chef plate"],
  ["Una buena nutrición previene diversas enfermedades crónicas.", "Good nutrition prevents various chronic diseases.", "healthy balanced meal fresh"],
  ["El control del consumo de calorías ayuda a mantener la forma física.", "Controlling calorie intake helps maintain physical fitness.", "fitness food count healthy"],
  ["El desarrollo del metaverso abre nuevas fronteras para la interacción digital.", "The development of the metaverse opens new frontiers for digital interaction.", "vr headset virtual reality user"],
  ["Planificar unas vacaciones tranquilas requiere anticipación y organización.", "Planning a peaceful vacation requires anticipation and organization.", "resort swimming pool palm trees"],
  ["El hospedaje en hoteles boutique ofrece experiencias personalizadas.", "Lodging in boutique hotels offers personalized experiences.", "boutique hotel reception lobby"],
  ["Confirmamos la reserva del vuelo con antelación.", "We confirmed the flight reservation in advance.", "hotel reservation smartphone app"],
  ["La política de cancelación permite un reembolso completo bajo condiciones.", "The cancellation policy allows a full refund under conditions.", "red cancelled stamp document"],
  ["La garantía del producto cubre reparaciones durante dos años.", "Product warranty covers repairs for two years.", "warranty certificate stamp seal"],
  ["La factura electrónica facilita la contabilidad de la empresa.", "Electronic invoicing facilitates corporate accounting.", "business invoice paper form"],
  ["Guardé el recibo de compra como comprobante de pago.", "I kept the purchase receipt as proof of payment.", "paper store receipt hand"],
  ["Ofrecen un descuento exclusivo para nuevos suscriptores.", "They offer an exclusive discount for new subscribers.", "percentage discount tag sale"],
  ["Aproveché la oferta especial de la tienda.", "I took advantage of the special shop offer.", "special offer sale sign shop"],
  ["La competencia leal estimula la innovación en el mercado.", "Fair competition stimulates market innovation.", "athletes racing finish line track"],
  ["El verdadero liderazgo inspira al equipo a superar sus límites.", "True leadership inspires the team to surpass its limits.", "leader guiding team meeting"],
  ["La negociación contractual requiere diplomacia y paciencia.", "Contractual negotiation requires diplomacy and patience.", "corporate business meeting table"],
  ["La colaboración interdisciplinaria genera hallazgos científicos revolucionarios.", "Interdisciplinary collaboration generates revolutionary scientific findings.", "team working together laptop"],
  ["La innovación tecnológica impulsa el desarrollo de nuevas industrias.", "Technological innovation drives the development of new industries.", "glowing lightbulb creative idea"],
  ["El joven emprendedor lanzó una startup tecnológica exitosa.", "The young entrepreneur launched a successful tech startup.", "young entrepreneur presentation pitch"],
  ["La financiación inicial permitió acelerar el crecimiento del proyecto.", "Initial financing allowed accelerating the project's growth.", "funding coins piggy bank investment"],
  ["Las teorías sobre el capitalismo examinan la acumulación de capital.", "Theories on capitalism examine capital accumulation.", "stock exchange floor traders"],
  ["La globalización conecta mercados y culturas a escala planetaria.", "Globalization connects markets and cultures on a planetary scale.", "digital globe connection network"],
  ["La democracia participativa fomenta el compromiso de la ciudadanía.", "Participatory democracy encourages citizen engagement.", "voting ballot box citizen vote"],
  ["La libertad de expresión es un pilar esencial en sociedades democráticas.", "Freedom of speech is an essential pillar in democratic societies.", "microphone speaking open auditorium"],
  ["La defensa de los derechos humanos debe ser universal e incondicional.", "Defending human rights must be universal and unconditional.", "diverse unity hands holding together"],
  ["Promover la igualdad de oportunidades beneficia a toda la sociedad.", "Promoting equality of opportunities benefits the whole society.", "balanced equality scale justice"],
  ["La diversidad de perspectivas enriquece el debate intelectual.", "Diversity of perspectives enriches intellectual debate.", "multicultural group smiling discussion"],
  ["La inclusión social garantiza que nadie quede excluido.", "Social inclusion guarantees that no one is left excluded.", "inclusive team circle unity"],
  ["La solidaridad de los voluntarios fue ejemplar durante la emergencia.", "Volunteer solidarity was exemplary during the emergency.", "helping hands support community"],
  ["El voluntariado corporativo apoya proyectos sociales de la comunidad.", "Corporate volunteering supports local community social projects.", "volunteers planting trees park"],
  ["Hicimos una donación a la organización benéfica.", "We made a donation to the charitable organization.", "charity donation box coins"],
  ["La fundación realiza proyectos educativos en zonas rurales.", "The foundation carries out educational projects in rural areas.", "charity foundation building school"],
  ["Una manifestación pacífica recorrió las calles de la capital.", "A peaceful demonstration marched through the streets of the capital.", "peaceful march protest banners"],
  ["Los trabajadores convocaron una huelga para exigir mejoras laborales.", "Workers called a strike to demand labor improvements.", "workers strike rally signs"],
  ["El sindicato negoció la revisión del convenio colectivo.", "The labor union negotiated the review of the collective agreement.", "union rally workers meeting"],
  ["La reforma constitucional fue debatida intensamente en el congreso.", "Constitutional reform was intensely debated in congress.", "historic legal constitution book"],
  ["El parlamento aprobó la ley por mayoría absoluta.", "Parliament passed the law by an absolute majority.", "parliament chamber debate vote"],
  ["Los senadores debatieron la propuesta durante la sesión plenaria.", "Senators debated the proposal during the plenary session.", "senate hall seats debate"],
  ["La diplomacia internacional evitó un conflicto armado mayor.", "International diplomacy prevented a major armed conflict.", "diplomats shaking hands agreement"],
  ["La embajada proporciona asistencia a los ciudadanos en el extranjero.", "The embassy provides assistance to citizens abroad.", "embassy building flags entrance"],
  ["Firmaron un tratado histórico de cooperación mutua.", "They signed a historic mutual cooperation treaty.", "signing international treaty document"],
  ["La alianza estratégica fortaleció la posición de ambas empresas.", "The strategic alliance strengthened the position of both companies.", "shaking hands global agreement"],
  ["La soberanía nacional reside en el pueblo.", "National sovereignty resides in the people.", "crown national seal constitution"],
  ["Celebraron la independencia del país con fuegos artificiales.", "They celebrated the country's independence with fireworks.", "fireworks celebration freedom sky"],
  ["La revolución tecnológica transformó los medios de comunicación.", "The technological revolution transformed communication media.", "historic monuments crowd movement"],
  ["El patriotismo responsable respeta a las demás naciones.", "Responsible patriotism respects other nations.", "saluting national flag respect"],
  ["La identidad cultural se transmite de generación en generación.", "Cultural identity is passed down from generation to generation.", "fingerprint biometrics identity security"],
  ["La personalidad de un individuo se moldea con la experiencia.", "An individual's personality is shaped by experience.", "diverse human faces masks expression"],
  ["El comportamiento ético es fundamental en los negocios.", "Ethical behavior is fundamental in business.", "honest handshake corporate ethics"],
  ["Una actitud positiva ante los retos nos ayuda a triunfar.", "A positive attitude towards challenges helps us succeed.", "positive confident posture stance"],
  ["La motivación personal es la fuerza que nos impulsa.", "Personal motivation is the force that drives us.", "athlete crossing finish line victory"],
  ["La naturaleza es una fuente constante de inspiración artística.", "Nature is a constant source of artistic inspiration.", "artist painting outdoor landscape"],
  ["La creatividad nos permite encontrar soluciones innovadoras.", "Creativity allows us to find innovative solutions.", "colorful paint splatters art studio"],
  ["La imaginación de los niños no tiene límites.", "Children's imagination has no limits.", "child wearing superhero cape soaring"],
  ["La curiosidad científica impulsa el descubrimiento de nuevos conocimientos.", "Scientific curiosity drives the discovery of new knowledge.", "child looking magnifying glass nature"],
  ["La sabiduría popular se refleja en los proverbios tradicionales.", "Popular wisdom is reflected in traditional proverbs.", "wise old owl book library"],
  ["La inteligencia emocional nos ayuda a gestionar el estrés.", "Emotional intelligence helps us manage stress.", "glowing brain synapse thoughts"],
  ["La conciencia ecológica ha aumentado en las nuevas generaciones.", "Ecological awareness has increased in new generations.", "mindful meditation sunrise nature"],
  ["La búsqueda de la espiritualidad aporta paz interior.", "The search for spirituality brings inner peace.", "zen stone balancing water pond"],
  ["Cada persona desarrolla su propia filosofía de vida.", "Each person develops their own philosophy of life.", "pathway sun rising over mountains"],
  ["El análisis exhaustivo del problema reveló detalles imprevistos.", "Comprehensive analysis of the problem revealed unexpected details.", "magnifying glass data charts review"],
  ["La arquitectura de vanguardia desafía las estructuras convencionales.", "Avant-garde architecture challenges conventional structures.", "futuristic glass building architecture"],
  ["Las teorías sociológicas ayudan a comprender los cambios urbanos.", "Sociological theories help understand urban changes.", "city network connections people"],
  ["La observación astronómica descubrió un exoplaneta distante.", "Astronomical observation discovered a distant exoplanet.", "deep space telescope galaxy stars"],
  ["La manipulación genética plantea dilemas éticos profundos.", "Genetic manipulation poses profound ethical dilemmas.", "dna helix laboratory research"],
  ["La física de partículas investiga los componentes fundamentales de la materia.", "Particle physics investigates fundamental components of matter.", "particle accelerator physics orbit"],
  ["Los modelos estadísticos son herramientas clave en la economía moderna.", "Statistical models are key tools in modern economics.", "financial analytics screen graphs"],
  ["La implementación del algoritmo optimizó el rendimiento del sistema.", "Algorithm implementation optimized system performance.", "high speed code algorithm server"],
  ["Los avances en robótica permiten realizar cirugías con alta precisión.", "Advances in robotics allow performing surgeries with high precision.", "robotic medical surgery arm"],
  ["El protocolo de ciberseguridad protegió los servidores corporativos.", "The cybersecurity protocol protected corporate servers.", "cyber security shield lock digital"],
  ["Las inversiones en sostenibilidad generaron beneficios a largo plazo.", "Sustainability investments generated long-term benefits.", "solar panels wind green field"],
  ["El derretimiento del hielo polar evidencia el impacto del calentamiento.", "Polar ice melting evidences the impact of global warming.", "melting iceberg polar bear ocean"],
  ["Las zonas de bajas emisiones buscan mitigar la contaminación urbana.", "Low emission zones aim to mitigate urban pollution.", "electric vehicle charging green city"],
  ["El compromiso con el reciclaje beneficia al planeta entero.", "Commitment to recycling benefits the entire planet.", "green recycling emblem eco"],
  ["La reserva marina protege la biodiversidad acuática amenazada.", "The marine reserve protects threatened aquatic biodiversity.", "scuba diver coral reef fish"],
  ["La deforestación acelerada amenaza la supervivencia de especies autóctonas.", "Accelerated deforestation threatens the survival of native species.", "rainforest trees sunlight green"],
  ["El plan de conservación recuperó poblaciones de fauna silvestre.", "The conservation plan recovered wild fauna populations.", "wild eagle flying mountains"],
  ["La transición energética requiere sustituir los combustibles fósiles.", "Energy transition requires replacing fossil fuels.", "wind turbine sunrise sky"],
  ["El proyecto de infraestructura conectará ambas regiones industriales.", "The infrastructure project will connect both industrial regions.", "suspension bridge sunset highway"],
  ["El plan de urbanismo integrará nuevas áreas verdes públicas.", "The urban planning project will integrate new public green areas.", "modern park city buildings"],
  ["Las facilidades para el alquiler benefician a los estudiantes universitarios.", "Rental facilities benefit university students.", "cozy student room study desk"],
  ["El museo custodia objetos del patrimonio histórico cultural.", "The museum guards objects of historical cultural heritage.", "museum golden artifacts exhibit"],
  ["La gastronomía local forma parte de la identidad cultural.", "Local gastronomy is part of cultural identity.", "traditional spanish dishes table"],
  ["La experiencia inmersiva en el metaverso ofreció nuevas perspectivas.", "The immersive metaverse experience offered new perspectives.", "person vr headset digital space"],
  ["El reembolso del importe se tramitó en cuarenta y ocho horas.", "The refund of the amount was processed within forty-eight hours.", "credit card refund confirmation"],
  ["La garantía extendida ofrece tranquilidad adicional al comprador.", "The extended warranty offers additional peace of mind to the buyer.", "guarantee seal ribbon gold"],
  ["La negociación colectiva fijó las condiciones salariales.", "Collective bargaining fixed salary conditions.", "corporate round table discussion"],
  ["La colaboración entre universidades impulsó la investigación médica.", "Collaboration between universities boosted medical research.", "researchers working lab together"],
  ["La innovación abierta fomenta el intercambio de ideas creativas.", "Open innovation encourages the exchange of creative ideas.", "glowing lightbulb network idea"],
  ["La aceleradora de proyectos ayudó a la startup a escalar.", "The project accelerator helped the startup to scale.", "rocket launch startup success"],
  ["La globalización exige adaptarse a mercados cada vez más competitivos.", "Globalization requires adapting to increasingly competitive markets.", "global connection network globe"],
  ["La democracia representativa requiere la participación de los ciudadanos.", "Representative democracy requires citizen participation.", "voters line ballot box election"],
  ["La defensa de los derechos humanos es un deber ético colectivo.", "Defending human rights is a collective ethical duty.", "holding hands human rights unity"],
  ["El principio de igualdad ante la ley es inalienable.", "The principle of equality before the law is inalienable.", "statue scales of justice law"],
  ["La diversidad de talentos aporta valor único a la organización.", "Diversity of talents brings unique value to the organization.", "diverse creative team meeting"],
  ["Las acciones de solidaridad social ayudaron a las familias necesitadas.", "Social solidarity actions helped families in need.", "volunteers packing food boxes"],
  ["La manifestación pacífica transcurrió con total tranquilidad.", "The peaceful demonstration proceeded in total tranquility.", "peaceful rally street banners"],
  ["La asamblea parlamentaria aprobó el presupuesto nacional.", "The parliamentary assembly approved the national budget.", "parliament chamber voting screen"],
  ["La diplomacia cultural fortalece los lazos entre diferentes naciones.", "Cultural diplomacy strengthens ties between different nations.", "diplomats shaking hands flags"],
  ["El tratado bilateral facilitó el comercio transfronterizo.", "The bilateral treaty facilitated cross-border trade.", "signing bilateral agreement pen"],
  ["La autodeterminación es un concepto clave en la soberanía.", "Self-determination is a key concept in sovereignty.", "freedom soaring eagle sky"],
  ["El valor del patriotismo integrador respeta la pluralidad.", "The value of integrative patriotism respects plurality.", "people celebrating national holiday"],
  ["La actitud positiva de los líderes motivó a todo el equipo.", "The leaders' positive attitude motivated the whole team.", "leader inspiring team applause"],
  ["La inspiración artística surgió contemplando la puesta de sol.", "Artistic inspiration arose while contemplating the sunset.", "painter easel sunset beach"],
  ["La imaginación sin límites permite crear mundos extraordinarios.", "Unlimited imagination allows creating extraordinary worlds.", "fantasy book glowing magic"],
  ["La sabiduría reside en escuchar y aprender de las experiencias.", "Wisdom resides in listening and learning from experiences.", "wise teacher listening student"]
];

// Load existing sentences
const rawExistingSentences = JSON.parse(fs.readFileSync('data/sentences.json', 'utf-8'));

const added_sentences = b2_sentences_raw.map((item, idx) => {
  const id = 9571 + idx;
  return {
    id,
    spanish: item[0],
    english: item[1],
    level: "B2",
    partOfSpeech: "phrase",
    imageQuery: item[2],
    image: {
      enabled: true,
      source: "pexels",
      url: null,
      photographer: null,
      photographerUrl: null,
      pexelsUrl: null
    }
  };
});

const all_sentences = [...rawExistingSentences, ...added_sentences];

fs.writeFileSync('data/sentences.json', JSON.stringify(all_sentences, null, 2), 'utf-8');

const csvHeader = "id,spanish,english,level,partOfSpeech,imageQuery\n";
const csvRows = all_sentences.map(s => `${s.id},"${s.spanish}","${s.english}",${s.level},${s.partOfSpeech},"${s.imageQuery}"`).join("\n");

fs.writeFileSync('data/sentences_800.csv', csvHeader + csvRows, 'utf-8');

console.log(`Successfully added ${added_sentences.length} B2 sentences! Total sentences dataset: ${all_sentences.length}.`);
