const fs = require('fs');

const a1_sentences = [
  ["Hola, ¿cómo estás?", "Hello, how are you?", "friends greeting wave"],
  ["Buenos días, señor.", "Good morning, sir.", "sunrise morning greeting"],
  ["Buenas tardes a todos.", "Good afternoon everyone.", "afternoon friends meeting"],
  ["Buenas noches, hasta mañana.", "Good night, see you tomorrow.", "starry night bed"],
  ["Me llamo Juan.", "My name is Juan.", "person introducing name"],
  ["¿Cómo te llamas?", "What is your name?", "two people meeting handshake"],
  ["Mucho gusto en conocerte.", "Nice to meet you.", "happy handshake meeting"],
  ["El gusto es mío.", "The pleasure is mine.", "polite smile handshake"],
  ["¿De dónde eres?", "Where are you from?", "world map travel flag"],
  ["Soy de España.", "I am from Spain.", "spanish flag madrid"],
  ["¿Dónde vives?", "Where do you live?", "cozy neighborhood house"],
  ["Vivo en Madrid.", "I live in Madrid.", "city street building"],
  ["Tengo veinte años.", "I am twenty years old.", "birthday cake candles"],
  ["¿Cuántos años tienes?", "How old are you?", "celebrating birthday party"],
  ["Por favor, siéntate.", "Please, sit down.", "chair sitting down"],
  ["Muchas gracias por todo.", "Thank you very much for everything.", "thank you note flower"],
  ["De nada, es un placer.", "You are welcome, it is a pleasure.", "friendly smiling wave"],
  ["Disculpe, ¿dónde está el baño?", "Excuse me, where is the bathroom?", "bathroom sign door"],
  ["No entiendo español muy bien.", "I do not understand Spanish very well.", "confused student book"],
  ["¿Puedes repetir, por favor?", "Can you repeat, please?", "listening ear gesture"],
  ["¿Hablas inglés?", "Do you speak English?", "speech bubbles languages"],
  ["Hablo un poco de español.", "I speak a little Spanish.", "person talking happy"],
  ["¿Qué hora es?", "What time is it?", "wrist watch clock time"],
  ["Son las tres de la tarde.", "It is three in the afternoon.", "clock showing three"],
  ["Hoy es lunes.", "Today is Monday.", "calendar page monday"],
  ["Mañana es mi cumpleaños.", "Tomorrow is my birthday.", "birthday present gift"],
  ["Ayer fue un día soleado.", "Yesterday was a sunny day.", "bright sun blue sky"],
  ["Me gustaría un café con leche.", "I would like a coffee with milk.", "latte coffee mug"],
  ["La cuenta, por favor.", "The bill, please.", "restaurant check receipt"],
  ["¿Cuánto cuesta este libro?", "How much does this book cost?", "price tag bookstore"],
  ["Es muy barato.", "It is very cheap.", "cheap price discount tag"],
  ["Es demasiado caro.", "It is too expensive.", "expensive luxury price"],
  ["Quiero comprar una manzana.", "I want to buy an apple.", "red fresh apple"],
  ["Tengo hambre.", "I am hungry.", "tasty food meal plate"],
  ["Tengo sed.", "I am thirsty.", "glass of cold water"],
  ["¿Tienes una mesa para dos?", "Do you have a table for two?", "restaurant dining table"],
  ["La comida está deliciosa.", "The food is delicious.", "gourmet meal plate"],
  ["¿Dónde está la estación de tren?", "Where is the train station?", "train station platform"],
  ["El autobús llega pronto.", "The bus is arriving soon.", "city bus arriving stop"],
  ["Necesito un taxi.", "I need a taxi.", "yellow city taxi cab"],
  ["El hotel es muy cómodo.", "The hotel is very comfortable.", "cozy hotel room bed"],
  ["Tengo una reserva a nombre de Ana.", "I have a reservation under the name Ana.", "hotel checkin reception"],
  ["¿Dónde puedo comprar un billete?", "Where can I buy a ticket?", "ticket kiosk station"],
  ["Me gusta leer libros.", "I like to read books.", "open book library"],
  ["Ella escucha música alegre.", "She listens to cheerful music.", "girl headphones music"],
  ["Nosotros jugamos al fútbol.", "We play soccer.", "friends playing soccer"],
  ["Ellos estudian en la biblioteca.", "They study in the library.", "students studying desk"],
  ["Mi perro es muy grande.", "My dog is very big.", "happy big golden retriever"],
  ["Su gato es pequeño y negro.", "Her cat is small and black.", "cute small black kitten"],
  ["La casa tiene una puerta roja.", "The house has a red door.", "cozy house red door"],
  ["El coche es azul.", "The car is blue.", "shiny blue sedan car"],
  ["Me gusta la fruta fresca.", "I like fresh fruit.", "fresh colorful fruit bowl"],
  ["Bebo agua todos los días.", "I drink water every day.", "drinking glass of water"],
  ["El sol brilla en el cielo.", "The sun shines in the sky.", "bright sun cloudless sky"],
  ["La luna es brillante esta noche.", "The moon is bright tonight.", "full moon night sky"],
  ["Hace mucho calor en verano.", "It is very hot in summer.", "sunny beach palm tree"],
  ["Hace frío en invierno.", "It is cold in winter.", "snowy winter landscape"],
  ["La flor es hermosa.", "The flower is beautiful.", "colorful blooming flower"],
  ["El árbol es muy alto.", "The tree is very tall.", "tall green pine tree"],
  ["Camino por el parque.", "I walk in the park.", "walking green park path"],
  ["El mar es grande y azul.", "The sea is big and blue.", "calm blue ocean wave"],
  ["Me gusta nadar en la playa.", "I like to swim at the beach.", "swimming ocean beach"],
  ["Mi familia es muy unida.", "My family is very close.", "happy family hugging"],
  ["Tengo dos hermanos y una hermana.", "I have two brothers and one sister.", "siblings smiling group"],
  ["Mi madre cocina muy bien.", "My mother cooks very well.", "mother cooking kitchen"],
  ["Mi padre trabaja en un banco.", "My father works in a bank.", "father office worker"],
  ["Mi abuela vive en el campo.", "My grandmother lives in the countryside.", "grandmother countryside cottage"],
  ["Tengo un amigo muy simpático.", "I have a very nice friend.", "two best friends smiling"],
  ["Voy al colegio por la mañana.", "I go to school in the morning.", "student walking school"],
  ["La clase de español empieza a las nueve.", "The Spanish class starts at nine.", "classroom teacher blackboard"],
  ["Escribo en mi cuaderno.", "I write in my notebook.", "hand writing notebook pen"],
  ["Tengo un bolígrafo azul.", "I have a blue pen.", "blue ink pen"],
  ["La mesa es de madera.", "The table is made of wood.", "wooden dining table"],
  ["La silla es cómoda.", "The chair is comfortable.", "comfy armchair seat"],
  ["La ventana está abierta.", "The window is open.", "open window fresh air"],
  ["La puerta está cerrada.", "The door is closed.", "closed wooden door"],
  ["Enciendo la luz.", "I turn on the light.", "glowing light bulb"],
  ["Apago la televisión.", "I turn off the television.", "living room smart tv"],
  ["El teléfono está sonando.", "The phone is ringing.", "ringing smartphone screen"],
  ["Envío un mensaje de texto.", "I send a text message.", "hand texting smartphone"],
  ["Abro la carta.", "I open the letter.", "opening paper envelope"],
  ["Compro pan en la panadería.", "I buy bread at the bakery.", "fresh bread bakery shop"],
  ["Tomo un vaso de leche.", "I drink a glass of milk.", "glass of fresh milk"],
  ["Como una ensalada saludable.", "I eat a healthy salad.", "fresh green salad bowl"],
  ["El queso es delicioso.", "The cheese is delicious.", "cheese wedge board"],
  ["La sopa está caliente.", "The soup is hot.", "steaming bowl of soup"],
  ["El helado es de chocolate.", "The ice cream is chocolate.", "chocolate ice cream cone"],
  ["Lavo las manos con jabón.", "I wash my hands with soap.", "washing hands soap lather"],
  ["Me cepillo los dientes.", "I brush my teeth.", "toothbrush brushing teeth"],
  ["Me ducho por la mañana.", "I shower in the morning.", "clean shower water stream"],
  ["Me visto con ropa limpia.", "I get dressed in clean clothes.", "choosing clean clothes shirt"],
  ["Voy a dormir en la cama.", "I am going to sleep in bed.", "cozy pillow blanket bed"],
  ["Tengo sueño.", "I am sleepy.", "yawning sleepy person"],
  ["Estoy cansado después del trabajo.", "I am tired after work.", "tired person relaxing couch"],
  ["Estoy muy feliz hoy.", "I am very happy today.", "joyful smiling face"],
  ["Ella está contenta.", "She is glad.", "happy woman smiling"],
  ["Él está triste.", "He is sad.", "sad person window rain"],
  ["El día es bonito.", "The day is nice.", "sunny clear sky day"],
  ["La noche es tranquila.", "The night is quiet.", "quiet starry night house"],
  ["Camino despacio.", "I walk slowly.", "peaceful slow walking"],
  ["El perro corre rápido.", "The dog runs fast.", "fast running dog grass"],
  ["Leo el periódico.", "I read the newspaper.", "reading morning newspaper"],
  ["Miro una película divertida.", "I watch a funny movie.", "watching movie popcorn"],
  ["Escucho la radio.", "I listen to the radio.", "vintage radio music"],
  ["Cocino la cena.", "I cook dinner.", "chef cooking frying pan"],
  ["Preparo el desayuno.", "I prepare breakfast.", "pancakes coffee breakfast"],
  ["Limpio la habitación.", "I clean the room.", "cleaning house tidy bedroom"],
  ["Abro la ventana para ver el sol.", "I open the window to see the sun.", "sunny window view"],
  ["Cierro la caja.", "I close the box.", "closing cardboard box"],
  ["Busco mis llaves.", "I search for my keys.", "searching house keys"],
  ["Encuentro mi cartera.", "I find my wallet.", "holding leather wallet cash"],
  ["Pago en efectivo.", "I pay in cash.", "paying cash bills"],
  ["Pago con tarjeta.", "I pay with card.", "paying credit card terminal"],
  ["El tren es rápido.", "The train is fast.", "high speed train tracks"],
  ["El coche va despacio.", "The car goes slowly.", "car driving slow road"],
  ["La tienda está abierta.", "The store is open.", "open store front sign"],
  ["El museo está cerrado.", "The museum is closed.", "museum entrance closed"],
  ["Entro en la cafetería.", "I enter the coffee shop.", "cozy coffee shop entrance"],
  ["Salgo de la oficina.", "I exit the office.", "walking out office building"],
  ["Llego a casa a las seis.", "I arrive home at six.", "arriving home front door"],
  ["Llevo mi mochila.", "I carry my backpack.", "person wearing backpack"],
  ["Traigo una tarta de manzana.", "I bring an apple pie.", "fresh baked apple pie"],
  ["Tomo el autobús número cinco.", "I take bus number five.", "city transit bus stop"],
  ["Doy un regalo a mi amigo.", "I give a gift to my friend.", "giving wrapped gift box"],
  ["Amo a mi familia.", "I love my family.", "heart gesture family"],
  ["Me gusta el color rojo.", "I like the color red.", "vibrant red color heart"],
  ["Quiero una pizza de queso.", "I want a cheese pizza.", "slice of hot cheese pizza"],
  ["Necesito ayuda con la tarea.", "I need help with homework.", "studying desk homework"],
  ["Sé hablar un poco de español.", "I know how to speak a little Spanish.", "speaking practice Spanish"],
  ["Conozco la ciudad de Barcelona.", "I know the city of Barcelona.", "barcelona sagrada familia"],
  ["Pienso que es una buena idea.", "I think it is a good idea.", "lightbulb idea thought"],
  ["Creo que tienes razón.", "I believe you are right.", "nodding agreeing smile"],
  ["Espero el autobús aquí.", "I wait for the bus here.", "waiting at bus stop bench"],
  ["Recuerdo ese día feliz.", "I remember that happy day.", "cherished photo memory"],
  ["Nunca olvido tu nombre.", "I never forget your name.", "friendly handshake greeting"],
  ["Aprendo palabras nuevas.", "I learn new words.", "vocabulary book study"],
  ["La profesora enseña bien.", "The teacher teaches well.", "teacher explaining classroom"],
  ["Estudio español todas las tardes.", "I study Spanish every afternoon.", "laptop book study desk"],
  ["Trabajo de lunes a viernes.", "I work Monday to Friday.", "office calendar desk"],
  ["Los niños juegan en el jardín.", "The children play in the garden.", "kids playing garden green"],
  ["Ella canta una canción bonita.", "She sings a pretty song.", "singing microphone stage"],
  ["Bailamos en la fiesta.", "We dance at the party.", "people dancing party lights"],
  ["Nado en el mar azul.", "I swim in the blue sea.", "swimming ocean water"],
  ["Reímos mucho juntos.", "We laugh a lot together.", "friends laughing together"],
  ["El bebé llora cuando tiene hambre.", "The baby cries when hungry.", "cute baby crying tear"],
  ["Ella sonríe siempre.", "She always smiles.", "cheerful woman smiling"],
  ["Ayudo a mi vecino.", "I help my neighbor.", "helping neighbor carrying box"],
  ["Lavo mi ropa los sábados.", "I wash my clothes on Saturdays.", "laundromat washing machine"],
  ["Corto el pan con el cuchillo.", "I cut the bread with the knife.", "slicing fresh loaf bread"],
  ["El plato se rompe.", "The plate breaks.", "broken ceramic plate"],
  ["Arreglo mi bicicleta.", "I fix my bicycle.", "repairing bicycle wheel tool"],
  ["Organizo mis papeles.", "I organize my papers.", "organizing desk folders paper"],
  ["Preparo un té caliente.", "I prepare hot tea.", "pouring hot tea cup"],
  ["El plato está limpio.", "The plate is clean.", "clean white ceramic plate"],
  ["La taza está sobre la mesa.", "The mug is on the table.", "coffee mug wooden table"],
  ["El vaso está lleno de agua.", "The glass is full of water.", "glass of clear water"],
  ["Uso el tenedor para comer.", "I use the fork to eat.", "fork meal plate"],
  ["La cuchara es de metal.", "The spoon is made of metal.", "silver soup spoon"],
  ["Limpio la boca con la servilleta.", "I wipe my mouth with the napkin.", "paper napkin dining"],
  ["El mantel es blanco.", "The tablecloth is white.", "dining table white tablecloth"],
  ["La cocina es grande.", "The kitchen is big.", "spacious modern kitchen"],
  ["El horno está caliente.", "The oven is hot.", "baking oven kitchen"],
  ["La nevera tiene comida.", "The refrigerator has food.", "open fridge full food"],
  ["Uso la sartén para cocinar.", "I use the frying pan to cook.", "frying pan stove cooking"],
  ["La olla hirviendo hace sopa.", "The boiling pot makes soup.", "boiling pot soup stove"],
  ["El almuerzo es a la una.", "Lunch is at one o'clock.", "sandwich lunch plate"],
  ["La cena es a las ocho.", "Dinner is at eight o'clock.", "family dining table dinner"],
  ["El desayuno está listo.", "Breakfast is ready.", "pancakes juice breakfast"],
  ["Comemos galletas de chocolate.", "We eat chocolate cookies.", "chocolate chip cookies milk"],
  ["El pastel de cumpleaños es grande.", "The birthday cake is big.", "birthday cake candles party"],
  ["Compro mermelada de fresa.", "I buy strawberry jam.", "jar of strawberry jam"],
  ["La mantequilla está en la nevera.", "The butter is in the fridge.", "yellow butter dish"],
  ["Agrego aceite a la ensalada.", "I add oil to the salad.", "pouring olive oil salad"],
  ["Pongo sal en la sopa.", "I put salt in the soup.", "salting soup bowl"],
  ["La cebolla es blanca.", "The onion is white.", "fresh white onion"],
  ["El tomate es rojo y dulce.", "The tomato is red and sweet.", "ripe red tomatoes vine"],
  ["Las patatas son sabrosas.", "The potatoes are tasty.", "baked potatoes plate"],
  ["La zanahoria es naranja.", "The carrot is orange.", "fresh orange carrots"],
  ["La lechuga es fresca y verde.", "The lettuce is fresh and green.", "fresh green lettuce head"],
  ["El plátano es amarillo.", "The banana is yellow.", "bunch of yellow bananas"],
  ["La naranja es jugosa.", "The orange is juicy.", "sliced juicy orange"],
  ["El limón es ácido.", "The lemon is sour.", "yellow lemon slices"],
  ["Las uvas son moradas.", "The grapes are purple.", "purple grapes vine"],
  ["La sandía es perfecta en verano.", "Watermelon is perfect in summer.", "sliced fresh watermelon"],
  ["La piña es una fruta tropical.", "Pineapple is a tropical fruit.", "fresh whole pineapple"],
  ["Compro un abrigo para el invierno.", "I buy a coat for the winter.", "warm winter coat rack"],
  ["Me pongo la chaqueta roja.", "I put on the red jacket.", "wearing red jacket outfit"],
  ["Llevo calcetines calientes.", "I wear warm socks.", "cozy winter wool socks"],
  ["Las botas son de cuero.", "The boots are made of leather.", "pair of leather boots"],
  ["Llevo gafas de sol en la playa.", "I wear sunglasses at the beach.", "wearing sunglasses beach"],
  ["El espejo está en el baño.", "The mirror is in the bathroom.", "bathroom wall mirror"],
  ["Uso la toalla limpia.", "I use the clean towel.", "folded clean bath towel"],
  ["El jabón huele muy bien.", "The soap smells very nice.", "bar of scented soap"],
  ["La almohada es muy suave.", "The pillow is very soft.", "soft white bed pillow"],
  ["La manta es bastante cálida.", "The blanket is quite warm.", "cozy warm knit blanket"],
  ["El sofá es grande y azul.", "The sofa is big and blue.", "living room blue sofa"],
  ["La lámpara está encendida.", "The lamp is turned on.", "table reading lamp glowing"],
  ["Las cortinas son elegantes.", "The curtains are elegant.", "window long curtains elegance"],
  ["Subo las escaleras despacio.", "I walk up the stairs slowly.", "climbing wooden stairs"],
  ["Uso el ascensor para subir.", "I use the elevator to go up.", "modern elevator doors"],
  ["La primavera trae muchas flores.", "Spring brings many flowers.", "spring blooming garden"],
  ["El verano es soleado y cálido.", "Summer is sunny and warm.", "sunny summer beach day"],
  ["El otoño cae hojas doradas.", "Autumn drops golden leaves.", "autumn golden leaves path"],
  ["El invierno trae nieve blanca.", "Winter brings white snow.", "snowy winter village trees"],
  ["Enero es el primer mes del año.", "January is the first month of the year.", "january calendar page"],
  ["El domingo me descanso en casa.", "On Sunday I rest at home.", "cozy sunday morning home"],
  ["Nos vemos esta noche a las siete.", "See you tonight at seven.", "evening city lights meet"],
  ["Vivo cerca del centro comercial.", "I live near the shopping mall.", "neighborhood houses near mall"],
  ["La playa está lejos de mi ciudad.", "The beach is far from my city.", "distant horizon ocean beach"],
  ["La caja está dentro de la casa.", "The box is inside the house.", "cardboard box inside room"],
  ["Los niños juegan fuera al aire libre.", "The children play outside in the open air.", "kids playing outdoor grass"]
];

const sentences_data = a1_sentences.map((item, idx) => {
  const id = 9001 + idx;
  return {
    id,
    spanish: item[0],
    english: item[1],
    level: "A1",
    partOfSpeech: "phrase",
    imageQuery: item[2],
    image: {
      enabled: true,
      source: "pexels",
      url: null,
      photographer: null,
      photographerUrl: null,
      pexelsUrl: null
    }
  };
});

fs.writeFileSync('data/sentences.json', JSON.stringify(sentences_data, null, 2), 'utf-8');

const csvHeader = "id,spanish,english,level,partOfSpeech,imageQuery\n";
const csvRows = sentences_data.map(s => `${s.id},"${s.spanish}","${s.english}",${s.level},${s.partOfSpeech},"${s.imageQuery}"`).join("\n");

fs.writeFileSync('data/sentences_200.csv', csvHeader + csvRows, 'utf-8');

console.log(`Successfully generated ${sentences_data.length} A1 sentences in data/sentences.json and data/sentences_200.csv!`);
